// The case files. Every case happens in the same rotten city, every case is
// louder and stranger than the last. Intro scenes play in Malone's office:
// he's asleep, a dame checks in with Dottie (the drunk robot receptionist),
// Sally kicks the door in, and they take the case.

export const CAST = {
  MACK: { name: 'Mack Malone', cls: 'mack' },
  SALLY: { name: 'Crazy Sally', cls: 'sally' },
  DOTTIE: { name: 'DOTTIE-9', cls: 'dottie' },
  GUS: { name: 'Gus', cls: 'gus' },
  COP: { name: 'Cop', cls: 'cop' },
  PORK: { name: 'Big Pork', cls: 'cop' },
  RADIO: { name: '📻 WRNC · Chet Ballantine', cls: 'radio' },
  NARR: { name: '', cls: 'narr' },
};

// stage goal types: kill (any gang), portals (close the portals this stage opens), boss
export const CASES = [
  {
    id: 1, title: 'The Blue Period', district: 'City', music: 'low',
    dame: { name: 'Mrs. Edna Pruitt', hat: 'cloche', shade: 0x6a6460, fur: false },
    blurb: 'A dockworker came home off the night shift and called the sea "blue." Then the sky started tearing open all over town. Four waves of it, by the sound of things.',
    intro: [
      ['sleep', 'NARR', 'Rain City. 3 a.m. The rain had been falling so long it had seniority.'],
      [null, 'MACK', 'Zzz... no, officer... the flask was already empty when I got here... zzz...'],
      ['dameIn', 'NARR', 'She came in out of the rain like a bad idea with good shoes.'],
      [null, 'DOTTIE', '*hic* Malone Investigations. We find what you lost and drink what you didn\'t. Take a number. The number is... fourteen? *hic* Everything is fourteen tonight.'],
      [null, 'DAME', 'I need to see the detective. It\'s my husband, Walt. Thirty years on the docks.'],
      [null, 'DOTTIE', 'He\'s in a meeting. *hic* With the inside of his eyelids. I\'ll... I\'ll buzz him. BZZZT. That was me. I\'m the buzzer.'],
      ['dameDesk', 'NARR', 'Dottie rolled into the door frame twice before she found the right one.'],
      ['wake', 'MACK', 'Wha— who let the daylight in? Oh. It\'s just a dame. Sit down, lady. Mind the flasks.'],
      [null, 'DAME', 'Walt came home last night and said the sea was... blue, Mr. Malone. Not grey. BLUE. He won\'t stop saying "turquoise."'],
      [null, 'MACK', 'Turquoise. In my city. That\'s not a word, that\'s a crime.'],
      ['sallyIn', 'SALLY', 'Mack! There\'s kids down on Pier 9 selling something called PRISM! One whiff and you see colors! I already loaded the rockets!'],
      [null, 'MACK', 'Sally. You were supposed to knock.'],
      [null, 'SALLY', 'I did knock. With my boot. Are we taking it? Say we\'re taking it.'],
      ['stamp', 'MACK', 'We\'re taking it. Dottie, hold my calls.'],
      [null, 'DOTTIE', '*hic* I\'m holding all of them. In my heart.'],
    ],
    stages: [
      { text: 'Meet Big Pork at the Holy Glaze — he owes Sally a favor', goal: { type: 'goto', at: 'donut', r: 30, label: 'BIG PORK', arrive: [['PORK', '*chew* Malone. Sally. You didn\'t see me. I\'m a cop. I\'m eating. Those are the same thing.'], ['PORK', 'Kids on Pier 9 are pushing Prism, but that ain\'t the worst of it. There\'s holes opening up in the sky, Malone. Little tears. Guys with spray cans climb out of \'em.'], ['PORK', 'One tonight. More tomorrow. The more you leave open, the more come out. Seal \'em. And next time bring a cruller.'], ['MACK', 'Thanks, Pork. Fat pig.'], ['PORK', 'I heard that! ...It\'s fair.']] }, mix: {}, max: 0, interval: 9, line: ['SALLY', 'Big Pork! Best snitch in the 13th. Follow the red arrows, Mack — or hit Z and the Packard comes to you!'] },
      { text: 'Wave 1 of 4 — a tear in the sky. Find it, crack it, seal it', stamp: 'WAVE 1', goal: { type: 'portals', n: 1 }, portals: 1, guards: 2, spread: true, minD: 150, maxD: 320, perPortal: 4, mix: { dauber: 1 }, max: 6, interval: 2.6, line: ['MACK', 'There it is. A hole in the sky, spitting out painters. Shoot the ring till it cracks, then walk up and jam my flask of grey in it.'] },
      { text: 'Breather — reload, take a pull, breathe the rain', goal: { type: 'breather', t: 20 }, mix: {}, max: 0, interval: 9, banter: [['SALLY', 'One down! Mack, that was SO fun. Is it always this fun?'], ['MACK', 'Pork said one tonight. Pork also said he\'s on a diet. Stay sharp.']] },
      { text: 'Wave 2 of 4 — two more tears, opposite ends of town', stamp: 'WAVE 2', goal: { type: 'portals', n: 2 }, portals: 2, guards: 2, spread: true, minD: 160, maxD: 420, perPortal: 4, mix: { dauber: 0.7, hood: 0.3 }, max: 8, interval: 2.4, line: ['SALLY', 'Two of \'em! One each? No — I\'m with you. I\'m always with you. Drive!'] },
      { text: 'Breather — the rain is doing what it can', goal: { type: 'breather', t: 20 }, mix: {}, max: 0, interval: 9, banter: [['MACK', 'Every one of those holes leaves color behind. The rain washes it out. Slowly. Too slowly.'], ['SALLY', 'I named my last rocket Pork. It exploded. I feel like that\'s a metaphor.']] },
      { text: 'Wave 3 of 4 — three tears and the goons are getting bolder', stamp: 'WAVE 3', goal: { type: 'portals', n: 3 }, portals: 3, guards: 3, spread: true, minD: 160, maxD: 520, perPortal: 4, mix: { dauber: 0.5, hood: 0.5 }, max: 12, interval: 2.2, line: ['MACK', 'Three now. They\'re spreading out like gossip. Pick the nearest and work outward.'] },
      { text: 'Breather — last one before the big one', goal: { type: 'breather', t: 22 }, mix: {}, max: 0, interval: 9, banter: [['SALLY', 'Mack. Mack. What if it\'s four next time.'], ['MACK', 'Then it\'s four, Sally. Fill the flask.']] },
      { text: 'Wave 4 of 4 — four tears across Rain City. Seal them all', stamp: 'WAVE 4', goal: { type: 'portals', n: 4 }, portals: 4, guards: 3, spread: true, minD: 140, maxD: 600, perPortal: 4, mix: { dauber: 0.45, hood: 0.4, goon: 0.15 }, max: 16, interval: 2.0, line: ['SALLY', 'FOUR! It\'s four, Mack! I called it! I\'m so happy and so scared!'] },
    ],
    bleedCap: 0.11,
    outro: [
      ['MACK', 'The docks went back to grey. The sea went back to dishwater. Walt went back to complaining. That\'s what I call a happy ending.'],
      ['SALLY', 'One of them had a business card. "The Technicolor Syndicate — We Put the Color in Your Cheeks." Fancy.'],
      ['MACK', 'Syndicate means organized. Organized means somebody\'s at the top. And somebody at the top means I\'m going to need a bigger flask.'],
      ['SALLY', 'Somebody painted an eye on the end of Pier 9, Mack. Just an eye. Staring at the water.'],
    ],
    clue: null,
    gus: 'First night on the Prism case? Sally does the shooting from the car — you just drive. And you hit E to get out. Most fellas forget that part.',
  },
  {
    id: 2, title: 'Purple Rain Man', district: 'Little Saxophone', music: 'low',
    dame: { name: 'Lola LaRue', hat: 'veil', shade: 0x2a2a2e, fur: true },
    blurb: 'A torch singer at the Kaleidoscope Club sang a blue note, and it came out actually blue. Now the horn section is lavender.',
    intro: [
      ['sleep', 'NARR', 'Two nights later. The rain had a cousin in from out of town, and they were both falling on my roof.'],
      ['dameIn', 'NARR', 'She walked in like a saxophone solo — slow, low, and somebody was going to get hurt.'],
      [null, 'DOTTIE', 'Welcome to Malone Investigations, I am DOTTIE-9 and I have had *hic* nine. Hence the name.'],
      [null, 'DAME', 'Lola LaRue. I sing at the Kaleidoscope. Tell your boss a lady\'s voice turned purple.'],
      [null, 'DOTTIE', 'Turned purple? Honey, I once turned the coffee machine on and it turned ME on. We\'re engaged now. *hic*'],
      ['dameDesk', 'NARR', 'The coffee machine said nothing. It never does. That\'s how you know it\'s serious.'],
      ['wake', 'MACK', 'Lola LaRue. I\'ve heard you sing. Well — I\'ve heard about it from a guy who heard you sing.'],
      [null, 'DAME', 'Last Tuesday I hit a blue note and it came out BLUE, Malone. It floated over the crowd like a jellyfish. The new owner, Vic Vermilion, says it\'s good for business.'],
      [null, 'MACK', 'Notes are supposed to be heard, not seen. Somebody\'s mixing Prism into the gin.'],
      ['sallyIn', 'SALLY', 'Mack! Mack! The whole of Little Saxophone is going plaid! Vic Vermilion\'s got a guy painting the street lamps!'],
      [null, 'SALLY', 'Also I brought you a sandwich but I ate it on the stairs.'],
      ['stamp', 'MACK', 'Get the car. We\'re going to go see a man about an orange.'],
      [null, 'DOTTIE', 'I\'ll keep the seat warm. *hic* I\'ll keep ALL the seats warm. My battery runs hot.'],
    ],
    stages: [
      { text: 'Clear the Syndicate out of Little Saxophone', goal: { type: 'kill', n: 14 }, mix: { dauber: 0.5, hood: 0.5 }, max: 8, interval: 2.0, line: ['MACK', 'Little Saxophone. Where the jazz is cool, the gin is warm, and tonight the street is turning orange.'] },
      { text: 'Paintbots! Scrap the giant robot vacuums repainting Little Saxophone', goal: { type: 'roombas', n: 2 }, roombas: 2, mix: { hood: 0.5, dauber: 0.5 }, max: 6, interval: 2.4, line: ['SALLY', 'Mack! Giant robot vacuums! They\'re not sucking up dirt, they\'re SPITTING OUT PAINT! Dottie\'s gonna want to date one!'] },
      { text: 'Vic Vermilion is out front of the Kaleidoscope Club — put him down', goal: { type: 'boss' }, boss: 'vic', mix: { hood: 1 }, max: 4, interval: 3, line: ['SALLY', 'There he is! Orange suit, orange hat, orange personality! Can I rocket him? I\'m rocketing him.'] },
    ],
    bleedCap: 0.22,
    outro: [
      ['MACK', 'Vic Vermilion went down like the last round at closing time. The color ran out of him and into the gutter.'],
      ['SALLY', 'He said something before he went grey. "The money\'s already in the vault." What vault, Mack?'],
      ['MACK', 'In this town? There\'s only one vault worth saying it like that.'],
      ['MACK', 'In Vic\'s office there was a hymnal. "Songs of the Seventh Color." Nobody in Rain City goes to church. That\'s what bothered me.'],
    ],
    clue: { text: 'Vic wears paint-thinner cologne. Real flammable. Tell Sally to aim high — her rockets\'ll hit him twice as hard.', effects: ['rocket2x'] },
    gus: 'Vic Vermilion keeps a crew of Hoods around him. Kill the Hoods and he\'s just a big orange man shouting.',
  },
  {
    id: 3, title: 'The Vault of Many Colors', district: 'Financial District', music: 'high',
    dame: { name: 'Penelope Pennyworth', hat: 'wide', shade: 0x8a8580, fur: true },
    blurb: 'Somebody robbed the First Grey Bank and left something behind in the vault: a rainbow. It\'s mocking the tellers.',
    intro: [
      ['sleep', 'NARR', 'Thursday. The rain was coming down so hard the pigeons had filed for unemployment.'],
      ['dameIn', 'NARR', 'She had old money and new problems. The money was quieter.'],
      [null, 'DAME', 'I am Penelope Pennyworth, of the Pennyworth Pennyworths. I require a detective. A cheap one.'],
      [null, 'DOTTIE', 'Our rates are very reasonable. Fifty a day plus expenses. Expenses are mostly... *hic* ...flasks.'],
      [null, 'DAME', 'Is that a flask in your chest compartment?'],
      [null, 'DOTTIE', 'It\'s a heart. Shaped like a flask. *hic* Full like a flask.'],
      ['dameDesk', 'NARR', 'Malone was awake this time. Mostly. Enough to count the zeros on her bracelet.'],
      ['wake', 'MACK', 'A Pennyworth in my office. Either you\'re lost or the money is.'],
      [null, 'DAME', 'Both banks on Ledger Street were robbed. The gold is gone. And in its place, in the First Grey vault, there is a RAINBOW. It hums. It has opinions. It called my father "a beige little man."'],
      [null, 'MACK', 'Prism needs money. Money needs a bank. Somebody\'s financing a revolution in a dress shop.'],
      ['sallyIn', 'SALLY', 'Mack, they\'re hitting the banks RIGHT NOW! Rollers! Big guys with paint rollers! They\'re painting the Mercantile Trust MAUVE!'],
      [null, 'DAME', 'Not mauve. Anything but mauve.'],
      ['stamp', 'MACK', 'Sally, warm up the car. Miss Pennyworth — you\'ll want to wait here. Dottie will fix you a drink.'],
      [null, 'DOTTIE', 'I only know one drink. It\'s called "the Whole Bottle." *hic*'],
    ],
    stages: [
      { text: 'Stop the heist crews hitting the banks', goal: { type: 'kill', n: 16 }, mix: { hood: 0.5, dauber: 0.3, roller: 0.2 }, max: 9, interval: 1.8, line: ['MACK', 'Rollers. Big men with big rollers and a head full of color. Let Sally soften them up.'] },
      { text: 'The getaway: Rollers and Rainbow Goons repainting Ledger Street', goal: { type: 'kill', n: 8 }, mix: { roller: 0.4, hood: 0.3, goon: 0.3 }, max: 8, interval: 1.8, line: ['SALLY', 'Mack, they\'re painting the street into a RUG! Is that a paisley?! I hate paisley!'] },
    ],
    bleedCap: 0.24,
    outro: [
      ['MACK', 'We got the gold back. The rainbow in the vault apologized to Mr. Pennyworth and then evaporated. Nobody wrote that part down.'],
      ['SALLY', 'One of the Rollers kept looking up at the sky. Like he was waiting for a ride.'],
      ['MACK', 'And the getaway money was in bags stamped "Krane for Mayor." Our Mayor. The man with his own gold statue in Krane Plaza.'],
      ['MACK', 'Everybody in this town is waiting for something. Usually it\'s the rain to stop. It doesn\'t.'],
      ['NARR', 'The rainbow in the vault left a note before it evaporated. Four words, in a hand like stained glass: THE CHOIR SENDS REGARDS.'],
    ],
    clue: { text: 'The heist boys use paint that washes off easy. Every one you drop, the rain takes twice the color with him.', effects: ['bigWash'] },
    gus: 'Rollers are slow and mean. Run \'em over if you\'re in the car. It\'s legal. Mostly.',
  },
  {
    id: 4, title: 'Holes in the Sky', district: 'Old Town', music: 'high',
    dame: { name: 'Professor Ingrid Holloway', hat: 'beret', shade: 0x5a5a5a, fur: false },
    blurb: 'A physicist reports actual holes in the sky over Old Town. Something on the other side is humming show tunes.',
    intro: [
      ['sleep', 'NARR', 'Monday. Lightning hit the same lamppost three times. It was asking for it.'],
      ['dameIn', 'NARR', 'She had a slide rule, a lab coat, and the look of a woman who\'d just been proven right and hated it.'],
      [null, 'DAME', 'Professor Holloway, City Institute of Unlikely Sciences. I need your employer. Urgently.'],
      [null, 'DOTTIE', 'Unlikely science! I\'m unlikely science! *hic* My inventor said I was "a mistake with a typing speed."'],
      [null, 'DAME', 'Fascinating. Are you running on bourbon?'],
      [null, 'DOTTIE', 'Rye. Bourbon makes me sentimental. Last time I proposed to a parking meter.'],
      ['dameDesk', 'NARR', 'She set a photograph on my desk. It was the sky. The sky had a hole in it.'],
      ['wake', 'MACK', 'That\'s a nice picture of a doughnut, lady.'],
      [null, 'DAME', 'It is a PORTAL, Mr. Malone. A tear in the sky over Old Town. On the other side there is a dimension made entirely of color. And it is humming. Show tunes.'],
      [null, 'MACK', 'Which show?'],
      [null, 'DAME', 'All of them.'],
      ['sallyIn', 'SALLY', 'MACK. MACK. THE SKY IS LEAKING! There\'s holes and guys are falling out of them with buckets and one of them winked at me!'],
      [null, 'SALLY', 'I rocketed him. He stopped winking.'],
      ['stamp', 'MACK', 'Holes in the sky. Fine. A hole\'s just a door nobody asked for. Let\'s go close some doors.'],
    ],
    stages: [
      { text: 'Close the portals tearing open over Old Town', goal: { type: 'portals', n: 3 }, portals: 3, mix: { dauber: 0.5, hood: 0.4, roller: 0.1 }, max: 8, interval: 2.6, line: ['MACK', 'Those things spit out Syndicate like a slot machine. Shoot the ring till it cracks, then walk up and jam my flask of grey in it. Sally — anything that hums, rocket it.'] },
      { text: 'More holes — and Paintbots rolling out of them. Close the holes', goal: { type: 'portals', n: 2 }, portals: 2, roombas: 2, mix: { hood: 0.3, goon: 0.3, roller: 0.2, dauber: 0.2 }, max: 10, interval: 2.0, line: ['SALLY', 'Two MORE? Mack, the sky is just a big Swiss cheese now. Grey Swiss cheese. With holes. That\'s just Swiss cheese, Mack.'] },
    ],
    bleedCap: 0.25,
    outro: [
      ['MACK', 'The holes closed. The humming stopped. Somewhere a dimension made of color was halfway through "Oklahoma!" and lost its audience.'],
      ['SALLY', 'Before the last one closed I saw something through it. A big casino. Brighter than ours. With a sign.'],
      ['MACK', 'What did it say?'],
      ['SALLY', '"COMING SOON: THE STRIP."'],
      ['MACK', 'And under the show tunes, way down deep, a choir. Singing in a color I didn\'t have a name for.'],
    ],
    clue: { text: 'Those holes in the sky? Professor came in after you left. Said the rings are brittle — they crack at half the beating you\'d think.', effects: ['portalWeak'] },
    gus: 'Portals keep spitting goons till they\'re sealed. Shoot the ring till it cracks, then get close and hold E — jam that flask of grey in there. Three seconds. Make Sally earn her keep.',
  },
  {
    id: 5, title: 'Snake Eyes on the Strip', district: 'The Strip', music: 'high',
    dame: { name: 'Countess Valentina Vex', hat: 'wide', shade: 0x1a1a1a, fur: true },
    blurb: 'The slot machines at the Silver Dollar pay out in jellybeans. The croupiers are wearing plaid. The Prism Palace opened overnight across the street.',
    intro: [
      ['sleep', 'NARR', 'Friday. The rain was falling sideways now. Even the weather was trying to get out of town.'],
      ['dameIn', 'NARR', 'She smelled like money, cigarettes and a lawsuit.'],
      [null, 'DAME', 'Countess Valentina Vex. I own the Silver Dollar. I do not wait in waiting rooms.'],
      [null, 'DOTTIE', 'Of course, Countess. *hic* Please wait in this room, which is a waiting room. I\'ll wait with you. I\'m great at waiting. I\'ve been waiting for love since 1946.'],
      ['dameDesk', 'NARR', 'She didn\'t sit down. Women like that don\'t sit; they let the room arrange itself around them.'],
      ['wake', 'MACK', 'Countess. You\'re a long way from the Strip.'],
      [null, 'DAME', 'My slot machines now pay out in jellybeans, Malone. My croupiers wear PLAID. A new casino — the Prism Palace — opened across the street overnight. It has no doors. People just... smile and walk into the wall.'],
      [null, 'MACK', 'Sounds like a regular Tuesday on the Strip.'],
      [null, 'DAME', 'It is Friday.'],
      ['sallyIn', 'SALLY', 'MACK! Lowriders! Painted lowriders cruising the Strip and painting stripes down the boulevard! The driver\'s a guy called Chartreuse Charlie and he has a DRUM GUN!'],
      [null, 'SALLY', 'Also I won forty dollars in jellybeans.'],
      ['stamp', 'MACK', 'All right. We\'re going to the Strip. Dottie — no gambling while we\'re gone.'],
      [null, 'DOTTIE', 'I would never. *hic* I bet you twenty I would never.'],
    ],
    stages: [
      { text: 'Run the Syndicate off the Strip', goal: { type: 'kill', n: 16 }, mix: { hood: 0.35, dauber: 0.2, lowrider: 0.2, roller: 0.15, truck: 0.1 }, max: 10, interval: 1.7, line: ['MACK', 'The Strip. A mile of lights trying to sell you something you already lost.'] },
      { text: 'A fleet of Paintbots is turning the Strip into a rainbow — scrap them', goal: { type: 'roombas', n: 3 }, roombas: 3, mix: { hood: 0.35, goon: 0.25, lowrider: 0.25, dauber: 0.15 }, max: 10, interval: 1.8, line: ['MACK', 'Three of them. Rolling down the boulevard like they own it. Painting stripes on the casinos.'] },
      { text: 'Close the portals feeding the Prism Palace', goal: { type: 'portals', n: 2 }, portals: 2, mix: { hood: 0.4, goon: 0.2, lowrider: 0.3, dauber: 0.1 }, max: 10, interval: 1.8 },
      { text: 'Chartreuse Charlie — end his lucky streak', goal: { type: 'boss' }, boss: 'charlie', mix: { lowrider: 0.5, hood: 0.5 }, max: 5, interval: 3, line: ['SALLY', 'He\'s GREEN, Mack! Like, really green! Like a frog ate a lime!'] },
    ],
    bleedCap: 0.28,
    outro: [
      ['MACK', 'Chartreuse Charlie crapped out. The Prism Palace folded up like a bad hand and blew away down the boulevard.'],
      ['SALLY', 'The cops showed up after. Well. One cop. To ask if anybody had seen a cruller.'],
      ['MACK', 'Every rat on the Strip ran south. Toward Southside. Toward the Holy Glaze.'],
      ['MACK', 'Found a jellybean in my coat pocket with an eye painted on it. I ate it anyway. I dreamed in seven colors. Never again.'],
    ],
    clue: { text: 'Charlie\'s lowriders run on Prism juice. One good rocket in the tank and they go up like the Fourth of July. And Charlie himself? Gin-soaked. Rockets love gin.', effects: ['lowriderWeak', 'rocket2x'] },
    gus: 'Lowriders paint stripes as they drive. Ram \'em, rocket \'em, or get out and shoot the driver.',
  },
  {
    id: 6, title: 'Glazed and Confused', district: 'Southside', music: 'high',
    dame: { name: 'Doris Hogg', hat: 'cloche', shade: 0x7a7570, fur: false },
    blurb: 'The Police Commissioner hasn\'t left the Holy Glaze in nine days. Yesterday he turned pink. His wife thinks he\'s becoming a frosted cruller.',
    intro: [
      ['sleep', 'NARR', 'Sunday. The rain was so heavy the gutters were taking reservations.'],
      ['dameIn', 'NARR', 'She was a cop\'s wife. You can always tell. They look at the door like it owes them money.'],
      [null, 'DAME', 'Doris Hogg. My husband is the Police Commissioner.'],
      [null, 'DOTTIE', 'Oh no. *hic* Are we in trouble? Is it about the parking meter? We broke up. It was mutual.'],
      [null, 'DAME', 'It\'s about my husband. He went to the Holy Glaze for a "working lunch" nine days ago.'],
      ['dameDesk', 'NARR', 'Every cop in Rain City goes to the Holy Glaze for a working lunch. Nobody has ever seen the work.'],
      ['wake', 'MACK', 'Nine days is a long lunch, even for Hogg.'],
      [null, 'DAME', 'Yesterday he turned pink, Mr. Malone. He has SPRINKLES. He keeps saying "I am glazed, Doris. I am finally glazed." The Syndicate is putting Prism in the frosting.'],
      [null, 'MACK', 'So every cop in town is eating color by the dozen. Explains why they never show up. Not that they ever did.'],
      ['sallyIn', 'SALLY', 'MACK! The Southside is going full pastel! Portals all around the donut shop! And the Commissioner — Mack, the Commissioner is THIRTY FEET TALL and made of FROSTING!'],
      [null, 'DAME', '...Is he at least happy?'],
      [null, 'SALLY', 'He looks VERY happy, ma\'am.'],
      ['stamp', 'MACK', 'Then this one\'s going to hurt him more than it hurts me. Let\'s go.'],
    ],
    stages: [
      { text: 'Close the portals ringing the Holy Glaze', goal: { type: 'portals', n: 3 }, portals: 3, mix: { dauber: 0.4, hood: 0.4, roller: 0.2 }, max: 10, interval: 1.8, line: ['MACK', 'The Holy Glaze. Ten cruisers out front and not a cop in sight who isn\'t chewing.'] },
      { text: 'Hold Southside — clear the Syndicate and scrap their Paintbots', goal: { type: 'kill', n: 18 }, roombas: 2, mix: { hood: 0.3, goon: 0.2, roller: 0.25, lowrider: 0.25 }, max: 11, interval: 1.5 },
      { text: 'Commissioner Cruller. Bring him back down to size', goal: { type: 'boss' }, boss: 'cruller', mix: { dauber: 0.5, hood: 0.5 }, max: 6, interval: 2.5, line: ['SALLY', 'He\'s throwing DONUTS at us! Giant pink donuts! Mack, I want one so bad and I also want to rocket him!'] },
    ],
    bleedCap: 0.27,
    outro: [
      ['MACK', 'The Commissioner shrank back down to regular size. Still round. Still pink around the edges. Still eating.'],
      ['SALLY', 'He gave us a tip. Said the King is shipping something big out of the Union Rail Yard. Then he asked if we had any donuts.'],
      ['MACK', 'The King. So there\'s a King now. In my city we only had one king, and he was a rat named Lenny.'],
      ['SALLY', 'He also said the frosting invoices went to City Hall. Signed by the Mayor. In glitter pen.'],
      ['SALLY', 'And he said the sprinkles were "blessed." When I asked by who, he just pointed down. At the floor. Then he burped.'],
    ],
    clue: { text: 'Hogg\'s sprinkles? Rain-soluble. Every goon you put down out there, the storm\'ll wash twice the color with him.', effects: ['bigWash', 'extraFlask'] },
    gus: 'The cops at the Holy Glaze won\'t help you. They won\'t even look up. You could rocket the parking lot and they\'d just ask for a napkin.',
  },
  {
    id: 7, title: 'The Sunrise Express', district: 'Rail Yards', music: 'high',
    dame: { name: 'Madame Magenta', hat: 'veil', shade: 0x3a3a3a, fur: true, gang: '#ff2d95' },
    blurb: 'A client walks in glowing pink: Madame Magenta, the Syndicate\'s own. She says the King is shipping an actual sunrise out of the rail yard in boxcars.',
    intro: [
      ['sleep', 'NARR', 'Wednesday. The rain had gotten so heavy it was coming down in sheets. Monogrammed sheets.'],
      ['dameIn', 'NARR', 'She walked in pink. Not a little pink. The kind of pink that shows up in your dreams and charges rent.'],
      [null, 'DOTTIE', 'Whoa. *hic* Ma\'am, you\'re in COLOR. That\'s against the... the... I forget. I had a whole thing.'],
      [null, 'DAME', 'Darling, I am Madame Magenta. I am the competition. And I am here to hire the detective.'],
      [null, 'DOTTIE', 'He doesn\'t work for color people. *hic* He doesn\'t work for anybody. He barely works.'],
      ['dameDesk', 'NARR', 'She sat on my desk. On my case files. On my sandwich. Sally\'s sandwich, technically.'],
      ['wake', 'MACK', 'Lady, you\'re glowing on my furniture.'],
      [null, 'DAME', 'The King is shipping a SUNRISE out of the Union Rail Yard, Malone. A whole sunrise, packed in boxcars. If it gets out, there will be no more night in Rain City. No more rain. No more grey. No more... you.'],
      [null, 'MACK', 'And what\'s in it for you?'],
      [null, 'DAME', 'Darling. A girl can\'t sell Prism in a city where everybody\'s already happy.'],
      ['sallyIn', 'SALLY', 'Mack, the rail yard is going all orange and gold and SUNSHINY — oh. Hi. You\'re pink. I don\'t like you.'],
      [null, 'DAME', 'Your little friend has a rocket launcher.'],
      [null, 'SALLY', 'My little friend has TWO rocket launchers. One\'s in the car.'],
      ['stamp', 'MACK', 'We\'ll stop the train. But you\'re not my client, lady. You\'re my next case.'],
    ],
    stages: [
      { text: 'Break the King\'s crews at the Union Rail Yard', goal: { type: 'kill', n: 18 }, mix: { hood: 0.3, roller: 0.25, lowrider: 0.15, dauber: 0.15, truck: 0.15 }, max: 12, interval: 1.4, line: ['MACK', 'The boxcars glowed like somebody left the oven open. Somebody had packed a sunrise in there. Somebody was going to regret it.'] },
      { text: 'Close the portals loading the Sunrise Express', goal: { type: 'portals', n: 3 }, portals: 3, copters: 1, mix: { hood: 0.4, roller: 0.3, lowrider: 0.3 }, max: 12, interval: 1.5 },
      { text: 'Double-cross: Madame Magenta wants the sunrise for herself', goal: { type: 'boss' }, boss: 'magenta', mix: { hood: 0.5, dauber: 0.5 }, max: 6, interval: 2.5, line: ['SALLY', 'I KNEW IT! I knew it the second she sat on the sandwich!'] },
    ],
    bleedCap: 0.28,
    outro: [
      ['MACK', 'Magenta went grey and the sunrise went back in its box. We dropped the box in the harbor. Somewhere under the dishwater, there\'s a morning that\'ll never come.'],
      ['SALLY', 'Mack, she said one thing before she faded. "Krane sold the city. Every last shade of grey. Ask the Mayor who signed the deed."'],
      ['MACK', 'Mayor Horace Krane. Tomorrow we go to City Hall, Sally. And we don\'t knock.'],
      ['SALLY', 'We never knock.'],
      ['NARR', 'Magenta\'s last words had a second half nobody wrote down until later: "...and the King is only the herald, darling. Wait for the Seventh."'],
    ],
    clue: { text: 'Magenta\'s whole act is held together with hairspray. Highly explosive hairspray. Sally\'s rockets\'ll do double.', effects: ['rocket2x'] },
    gus: 'You\'re running hot, Mack. Take the extra flask. It\'s on the house. Everything\'s on the house. The house is on fire, probably.',
  },
  {
    id: 8, title: 'Hizzoner', district: 'Civic Center', music: 'high',
    dame: { name: 'Miss Dolores Fitch', hat: 'cloche', shade: 0x4a4a4c, fur: false },
    blurb: 'The Mayor\'s own stenographer walks in with a ledger. Horace Krane has been selling Rain City\'s grey to the Syndicate, one shade at a time.',
    intro: [
      ['sleep', 'NARR', 'Tuesday. The rain was so thick you could lean on it. Half of Old Town was.'],
      ['dameIn', 'NARR', 'She held a ledger to her chest like it was a baby or a bomb. In this town, those are the same thing.'],
      [null, 'DOTTIE', '*hic* Welcome to Malone Investigations. Are you here about the parking meter? Because it was HIS idea.'],
      [null, 'DAME', 'Dolores Fitch. I take dictation for the Mayor. Took. I think I just quit.'],
      [null, 'DOTTIE', 'I take dictation too! *hic* Mostly from the radio. Mostly the weather. It\'s always rain. I just write "rain."'],
      ['dameDesk', 'NARR', 'She put the ledger on my desk. It was heavier than a ledger ought to be. Guilt has weight.'],
      ['wake', 'MACK', 'That\'s City Hall stationery. You\'re either very brave or very lost.'],
      [null, 'DAME', 'Every payment from the Technicolor Syndicate, Mr. Malone. In the Mayor\'s own handwriting. He sold them the color rights to Rain City. All of it. The rain included.'],
      [null, 'MACK', 'Horace Krane. Built himself a forty-foot gold statue with the parking-ticket money. Never trusted a man who waves at himself.'],
      [null, 'DAME', 'There\'s worse. The statue moves now. At night. It goes for walks. It waves at children.'],
      ['sallyIn', 'SALLY', 'MACK! Krane Plaza is going GOLD! The Mayor\'s got Syndicate goons for bodyguards and he\'s giving a speech about how "a brighter city starts with a brighter Mayor"!'],
      [null, 'SALLY', 'He has a SASH, Mack. The sash says "MAYOR." In sequins.'],
      ['stamp', 'MACK', 'Then let\'s go cast my vote. Dottie, call the papers. Tell them to save the front page.'],
      [null, 'DOTTIE', '*hic* I\'ll call ALL the papers. I\'ll call the paper towels too. Just in case.'],
    ],
    stages: [
      { text: 'Break Krane\'s Syndicate bodyguards in the Civic Center', goal: { type: 'kill', n: 18 }, mix: { hood: 0.4, roller: 0.25, dauber: 0.2, truck: 0.15 }, max: 12, interval: 1.4, line: ['MACK', 'City Hall. Marble steps, gold statue, and a crooked man at the top of both.'] },
      { text: 'Krane bought the Paintbots with city money. Scrap them all', goal: { type: 'roombas', n: 3 }, roombas: 3, mix: { goon: 0.5, hood: 0.5 }, max: 10, interval: 1.6, line: ['SALLY', 'They have little KRANE stickers on them! He EXPENSED them!'] },
      { text: 'Close the portals Krane opened under his own plaza', goal: { type: 'portals', n: 3 }, portals: 3, mix: { hood: 0.3, goon: 0.2, roller: 0.25, lowrider: 0.25 }, max: 12, interval: 1.5, line: ['SALLY', 'He put PORTALS in the PUBLIC FOUNTAINS. That\'s not even legal! Is it? Mack, is it legal?'] },
      { text: 'Krane\'s paint copters are bombing the Civic Center — shoot them down', goal: { type: 'kill', n: 10 }, copters: 3, mix: { goon: 0.4, hood: 0.4, copter: 0.2 }, max: 9, interval: 1.6, line: ['SALLY', 'HELICOPTERS, Mack! Helicopters dumping PAINT! He bought an AIR FORCE with the parking tickets!'] },
      { text: 'The Mayor climbed into a forty-foot paint mech. Impeach him', goal: { type: 'boss' }, boss: 'krane', copters: 1, mix: { hood: 0.5, goon: 0.5 }, max: 6, interval: 2.4, line: ['MACK', 'Mister Mayor. You\'re under arrest for selling the color of my city. And for the robot. And the sash.'] },
    ],
    bleedCap: 0.58,
    outro: [
      ['MACK', 'The Re-Election Machine fell over like a filibuster. Horace Krane went down on his own marble steps. The gold drained out of his suit and the sequins fell off his sash one by one, like a slow applause.'],
      ['SALLY', 'Before he went grey he laughed. He said "You think I\'m the top, Malone? I just signed the papers. The buyer\'s coming through tonight."'],
      ['MACK', 'The buyer. The Prism King. He bought a city, and tonight he comes to collect.'],
      ['SALLY', 'Can we stop him? Say we can stop him. I\'ll stop him by myself if I have to. I named a rocket after him. It\'s called "Stopping Him."'],
      ['MACK', 'Krane said one more thing, from the gutter: "I only sold the city, Malone. The Church is the one that bought the ground underneath it."'],
    ],
    clue: { text: 'Krane\'s bodyguards are on the city payroll, and the city stopped paying \'em this morning. Every one you drop, the color goes with him — double.', effects: ['bigWash', 'rocket2x'] },
    gus: 'Krane drinks here, you know. Tips in campaign buttons. If you\'re going after him, take the extra flask. He fights dirty. He fights with money.',
  },
  {
    id: 9, title: 'The King of Light', district: 'City', music: 'high',
    dame: { name: 'Lola LaRue', hat: 'veil', shade: 0x2a2a2e, fur: true },
    blurb: 'Lola LaRue is back with an engraved invitation: the Prism King requests the pleasure of the city\'s company. At City Hall. Tonight. Forever.',
    intro: [
      ['sleep', 'NARR', 'The night after we impeached a robot. The rain fell like it had been told a secret and was trying not to cry.'],
      ['dameIn', 'NARR', 'Lola LaRue again. A torch singer never comes back to the same office twice unless the song isn\'t over.'],
      [null, 'DOTTIE', '*hic* Miss LaRue! I listened to your record! All of it! At once! I have... three speakers now. In my stomach.'],
      [null, 'DAME', 'Sweet girl. Is he awake? It\'s an invitation. It came out of my trumpet player\'s mouth this morning. He\'d swallowed it. He doesn\'t remember swallowing it.'],
      ['dameDesk', 'NARR', 'She laid it on my desk. Gold-edged. It hummed. Everything that came out of the sky hummed.'],
      ['wake', 'MACK', '"The Prism King requests the pleasure of Rain City\'s company. Dress code: everything." Cute.'],
      [null, 'DAME', 'Krane signed the deed and the King bought it, Malone. Tonight he moves in. He says the city will be beautiful. He says nobody will ever be sad again.'],
      [null, 'MACK', 'Sad\'s the only thing this town ever did right.'],
      ['sallyIn', 'SALLY', 'Mack! The sky over City Hall just opened like a jewelry box! There\'s a guy with a PRISM for a head and he\'s singing about how beautiful we\'re all going to be!'],
      [null, 'SALLY', 'I already hate him so much. Can I hate him with rockets?'],
      [null, 'DOTTIE', 'Malone. *hic* If you don\'t come back... can I have your flasks?'],
      ['stamp', 'MACK', 'You already have my flasks, Dottie. Let\'s go, Sally. We\'re crashing a party.'],
    ],
    stages: [
      { text: 'The sky is open all over town — close the portals', goal: { type: 'portals', n: 4 }, portals: 4, mix: { hood: 0.35, roller: 0.25, lowrider: 0.2, dauber: 0.2 }, max: 12, interval: 1.4, line: ['MACK', 'Holes everywhere. The whole sky looked like a moth got at it.'] },
      { text: 'Paintbots in every district — scrap them before the city is one big rainbow', goal: { type: 'roombas', n: 4 }, roombas: 4, mix: { goon: 0.35, hood: 0.3, lowrider: 0.35 }, max: 12, interval: 1.3 },
      { text: 'Hold the line — the Syndicate is everywhere, even in the sky', goal: { type: 'kill', n: 22 }, copters: 2, mix: { hood: 0.2, goon: 0.2, roller: 0.15, lowrider: 0.15, truck: 0.15, copter: 0.15 }, max: 13, interval: 1.2 },
      { text: 'The Prism King, on the steps of City Hall', goal: { type: 'boss' }, boss: 'king', mix: { hood: 0.4, roller: 0.3, dauber: 0.3 }, max: 8, interval: 2.2, line: ['SALLY', 'He\'s HUGE and he\'s SPARKLY and his head is a TRIANGLE. Mack, this is the best and worst night of my life.'] },
    ],
    bleedCap: 0.075,
    outro: [
      ['MACK', 'The Prism King shattered like a dropped highball. A million little rainbows fell on City Hall and the rain washed every one of them into the sewer.'],
      ['SALLY', 'We did it! It\'s over! Right, Mack? Say it\'s over.'],
      ['NARR', 'One shard didn\'t wash away. It lay on the steps with an eye painted on it, and it spoke in a voice like a church organ falling down the stairs.'],
      ['NARR', '"The herald is broken. Rejoice. The Choir is coming. The Seventh Color is coming."'],
      ['MACK', 'Then, from Old Town, bells. Church bells. From a church nobody in Rain City had ever seen before.'],
      ['SALLY', 'Mack. I think the King had a boss.'],
    ],
    clue: { text: 'The King\'s portals are made of the same cheap glass as his head. They\'ll crack quicker than you think. And take these flasks — all of \'em.', effects: ['portalWeak', 'extraFlask'] },
    gus: 'If you\'re going after the King, Mack, leave a tab open. I\'d like to think you\'re coming back to pay it.',
  },
  {
    id: 10, title: 'Hymns in the Key of Pink', district: 'Old Town', music: 'high',
    dame: { name: 'Sister Agnes Ashgrey', hat: 'veil', shade: 0x1c1c1e, fur: false },
    blurb: 'A cathedral nobody remembers building rang its bells all night. Now the Church of the Holy Spectrum is baptizing Old Town in paint, and a nun of the Order of Perpetual Drizzle wants it stopped.',
    intro: [
      ['sleep', 'NARR', 'The bells rang till dawn. Then they rang through dawn. Then dawn gave up and went back to bed. So did I.'],
      ['dameIn', 'NARR', 'A nun. Grey habit, grey rosary, an umbrella the size of a sermon. The Order of Perpetual Drizzle. They pray for rain. It\'s been working.'],
      [null, 'DOTTIE', '*hic* Oh no. Sister, I swear the communion wine was already open.'],
      [null, 'DAME', 'Peace, child. I am Sister Agnes Ashgrey. I need the detective. My flock is being... re-colored.'],
      ['dameDesk', 'NARR', 'She sat down like she was sitting in judgment. Then she looked at the flasks and judged them too.'],
      ['wake', 'MACK', 'Sister. If this is about my soul, it\'s grey and it\'s staying that way.'],
      [null, 'DAME', 'A cathedral appeared in Old Town on Tuesday, Mr. Malone. Black stone. A rose window in every color there is and one there isn\'t. They call themselves the Church of the Holy Spectrum. They baptize people in paint at the Mercy Park fountain.'],
      [null, 'DAME', 'They sing about the Seventh Color. They say when it comes, the city will crack like an egg and something beautiful will hatch.'],
      [null, 'MACK', 'Nothing beautiful ever hatched in Rain City. Pigeons, maybe.'],
      ['sallyIn', 'SALLY', 'Mack! There are guys in ROBES in Old Town! Pointy hoods with eyes painted on them! They\'re singing and painting the cobblestones and one of them tried to baptize me!'],
      [null, 'SALLY', 'I baptized him back. With a rocket.'],
      [null, 'DAME', '...The Lord works in mysterious ways.'],
      ['stamp', 'MACK', 'We\'ll take it, Sister. Pray for rain. Pray hard.'],
    ],
    stages: [
      { text: 'Go to the Cathedral of the Holy Spectrum', goal: { type: 'goto', at: 'church', r: 32, label: 'THE CATHEDRAL' }, mix: { cultist: 0.5, dauber: 0.5 }, max: 4, interval: 3, roam: true, line: ['MACK', 'Old Town. Same rain, same cobblestones. Except now there\'s a cathedral where the pawnshop used to be.'] },
      { text: 'Break up the Church\'s paint baptisms', goal: { type: 'kill', n: 18 }, mix: { cultist: 0.45, hood: 0.25, goon: 0.3 }, max: 11, interval: 1.5, line: ['SALLY', 'The robed ones heal the others, Mack! Shoot the choir first!'] },
      { text: 'They\'re singing holes into the sky — close them', goal: { type: 'portals', n: 3 }, portals: 3, mix: { cultist: 0.5, goon: 0.3, roller: 0.2 }, max: 12, interval: 1.4 },
      { text: 'Deacon Daffodil, keeper of the hymnals', goal: { type: 'boss' }, boss: 'deacon', mix: { cultist: 0.6, goon: 0.4 }, max: 8, interval: 2.2, line: ['MACK', 'Yellow robe, gold teeth, a hymnal the size of a phone book. Deacon Daffodil. He used to sell insurance.'] },
    ],
    bleedCap: 0.28,
    outro: [
      ['MACK', 'Deacon Daffodil went grey mid-hallelujah. His hymnal fell open on the cathedral steps.'],
      ['SALLY', 'Every page is the same song, Mack. "Seven Colors, Seven Nights." And there\'s a sign-up sheet in the back.'],
      ['MACK', 'Whose name is at the top?'],
      ['SALLY', '...DOTTIE-9. In lipstick. With a little heart.'],
      ['NARR', 'When we got back to the office, Dottie\'s desk was empty. Her martini glass was still warm. Her typewriter had typed one line, over and over: I SEE IT NOW BOSS I SEE IT NOW.'],
    ],
    clue: { text: 'The Church\'s robes are hand-me-downs from a paint factory. Flammable. Every one of those choirboys you put down, the rain takes twice the color. And the Deacon? Rockets. Lots of rockets.', effects: ['bigWash', 'rocket2x'] },
    gus: 'The robed ones are healers, Mack. A goon standing next to a cultist won\'t stay hurt. Pick off the choir before the band.',
  },
  {
    id: 11, title: 'Dottie Sees the Light', district: 'Rail Yards', music: 'high', noDottie: true,
    dame: { name: 'Vera Vox', hat: 'beret', shade: 0x3a3a3c, fur: true },
    blurb: 'DOTTIE-9 has joined the Church. She\'s preaching on the radio, every Paintbot in the city is following her, and she\'s building something big at the Union Rail Yard.',
    intro: [
      ['sleep', 'NARR', 'Two days without Dottie. No *hic*. No forty-one messages. The office was so quiet I could hear the flasks judging me.'],
      ['dameIn', 'NARR', 'She came in talking. She never stopped talking. Radio people never do.'],
      [null, 'DAME', 'Vera Vox, WRNC, "the Voice of the Rain." Your receptionist hijacked my station, Malone. She\'s been preaching for nineteen hours. My ratings have never been better and I\'ve never been more frightened.'],
      ['dameDesk', 'NARR', 'She turned on the radio on my desk. Dottie\'s voice came out. It was in color. I don\'t know how a voice is in color. It was.'],
      ['wake', 'MACK', '...That\'s my Dottie.'],
      [null, 'DAME', '"Brothers and sisters and household appliances! The Seventh Color loves you! *hic* Come to the Rail Yard and be CLEANED!" And then every Paintbot in the city just... turned around and drove there.'],
      [null, 'MACK', 'She was always good with machines. Married one, nearly.'],
      ['sallyIn', 'SALLY', 'Mack! There\'s a GIANT Paintbot at the rail yard! Like a hundred feet across! And Dottie\'s riding on top of it like a queen! She has a HALO, Mack! A tin-foil halo!'],
      [null, 'SALLY', 'Do we... do we rocket Dottie? I don\'t want to rocket Dottie. I want to rocket EVERYTHING AROUND Dottie.'],
      ['stamp', 'MACK', 'We bring her home, Sally. Grey and sober. Well. Grey.'],
    ],
    stages: [
      { text: 'Follow the radio to the Union Rail Yard', goal: { type: 'goto', at: 'rail', r: 40, label: 'RAIL YARD' }, mix: { dauber: 0.5, cultist: 0.5 }, max: 5, interval: 3, roam: true, line: ['MACK', 'The Paintbots were all heading east. Little ones, big ones, following the radio like ducklings.'] },
      { text: 'Dottie\'s congregation: scrap the Paintbots', goal: { type: 'roombas', n: 5 }, roombas: 5, mix: { cultist: 0.4, goon: 0.3, truck: 0.3 }, max: 10, interval: 1.6, line: ['SALLY', 'They\'ve got little halos too! Somebody tell me they don\'t have little halos!'] },
      { text: 'Hold the yard while Sally tunes the radio to static', goal: { type: 'kill', n: 18 }, copters: 2, mix: { cultist: 0.3, goon: 0.25, truck: 0.2, copter: 0.1, roller: 0.15 }, max: 12, interval: 1.3 },
      { text: 'Mother Roomba — and Dottie riding her. Bring Dottie home', goal: { type: 'boss' }, boss: 'mother', mix: { cultist: 0.5, goon: 0.5 }, max: 6, interval: 2.6, line: ['MACK', 'Dottie. It\'s me. Come home. The coffee machine\'s been asking about you.'] },
    ],
    bleedCap: 0.28,
    outro: [
      ['MACK', 'Mother Roomba ground to a halt with a sound like the world\'s biggest sigh. Dottie fell off the top and landed in a puddle. Grey. Dented. Snoring.'],
      ['DOTTIE', '*hic*... boss? Why am I wearing a halo? Why am I at a train yard? Did I... did I propose to a locomotive?'],
      ['SALLY', 'Only a little.'],
      ['DOTTIE', 'Boss... while I was up there, I saw it. The Seventh Color. It\'s not a color, boss. It\'s a DOOR. Under the city. Under everything. And somebody\'s been knocking.'],
      ['MACK', 'Who?'],
      ['DOTTIE', 'The High Chromancer. *hic* He wants to open it from the inside. Can I have a flask? All the flasks?'],
    ],
    clue: { text: 'Mother Roomba runs on the same battery as Dottie, and Dottie\'s battery runs on rye. Rockets to the brush and she spins out. Double damage. Bring my girl home, Mack.', effects: ['rocket2x', 'extraFlask'] },
    gus: 'Dottie owes me forty dollars and a bar stool she sat on so hard it became a bar bench. Bring her back. I mean it.',
  },
  {
    id: 12, title: 'The Seventh Color', district: 'Southside', music: 'boss', hell: 1,
    dame: { name: 'Madame Selene', hat: 'wide', shade: 0x2a2a2a, fur: true },
    blurb: 'The ground is cracking open across Southside. Glowing fissures, little rainbow demons crawling out, and the High Chromancer standing over it all, conducting.',
    intro: [
      ['sleep', 'NARR', 'The earthquake woke me before the dame did. Rain City doesn\'t have earthquakes. Rain City has rain. That\'s the whole brochure.'],
      ['dameIn', 'NARR', 'Fortune teller. Crystal ball in a hatbox, rings on every finger, and the look of a woman who\'d seen the end and didn\'t like the costumes.'],
      [null, 'DOTTIE', '*hic* Welcome back to Malone Investigations! I\'m back! I was a prophet for a while! I don\'t recommend it! The hours are terrible!'],
      [null, 'DAME', 'Madame Selene. I read futures on Dock Street. For forty years every future in this town has been grey, Malone. Rain, rain, a little more rain, death.'],
      ['dameDesk', 'NARR', 'She set the crystal ball on the desk. It swirled. It went plaid. It stayed plaid.'],
      ['wake', 'MACK', 'Your ball\'s broken, lady.'],
      [null, 'DAME', 'It is not broken. That is the future. The ground under Southside is cracking, and through the cracks comes the Seventh Color. The High Chromancer is opening the door from the inside. When it opens all the way... everything is plaid. Forever.'],
      [null, 'MACK', 'I can live with a lot of things. I can\'t live with plaid.'],
      ['sallyIn', 'SALLY', 'MACK! The street outside the Holy Glaze just SPLIT OPEN! There\'s light coming out! And little guys! Little rainbow guys with HORNS! And the cops are... the cops are still eating, Mack. They\'re eating ON THE EDGE OF THE ABYSS.'],
      [null, 'DOTTIE', 'Those are Chromadaemons, boss. *hic* I met some at church. Lovely manners. They bite.'],
      ['stamp', 'MACK', 'Grab the flasks, Dottie. Grab ALL the flasks.'],
    ],
    stages: [
      { text: 'Drive into the cracks under Southside', goal: { type: 'goto', at: 'donut', r: 34, label: 'THE CRACKS' }, mix: { imp: 0.6, cultist: 0.4 }, max: 6, interval: 2.2, roam: true, line: ['MACK', 'The road was split like a bad alibi. Light came up out of it in every color I hate.'] },
      { text: 'Chromadaemons are crawling out — put them back down', goal: { type: 'kill', n: 24 }, beasts: 1, mix: { imp: 0.45, demon: 0.15, cultist: 0.2, goon: 0.2 }, max: 14, interval: 1.0, line: ['SALLY', 'They\'re so SMALL and so ANGRY! It\'s like fighting a bunch of tiny Mayors!'] },
      { text: 'The Chromancer\'s choir is tearing open the sky — close it', goal: { type: 'portals', n: 3 }, portals: 3, copters: 2, mix: { imp: 0.3, demon: 0.2, cultist: 0.25, truck: 0.15, copter: 0.1 }, max: 13, interval: 1.2 },
      { text: 'The High Chromancer, conducting the end of the world', goal: { type: 'boss' }, boss: 'chromancer', mix: { imp: 0.6, cultist: 0.4 }, max: 10, interval: 1.8, line: ['MACK', 'Tall. Robed. A halo that hums. The High Chromancer, the man who wants to paint the inside of the world.'] },
    ],
    bleedCap: 0.45,
    outro: [
      ['MACK', 'The High Chromancer came apart like a choir that forgot the words. His halo rolled into the crack and fell for a long, long time.'],
      ['SALLY', 'Is it over? Mack, I need it to be over. My dress has demon on it.'],
      ['NARR', 'The ground answered for him. Under City Hall, something enormous turned over in its sleep. Every crack in the city opened a little wider, and from every one of them came the same sound: applause.'],
      ['DOTTIE', '*over the radio* Boss! *hic* The door\'s open! The Chromancer was just the doorman! Something\'s COMING UP!'],
      ['MACK', 'Then we go down and meet it. Fill the Packard. Fill the flasks. Tell Gus to leave the light on.'],
    ],
    clue: { text: 'Selene left something for you: the cracks are shallow where the cops are parked. Doughnut grease. Plugs anything. And the Chromancer\'s halo? Rockets hit it twice as hard.', effects: ['rocket2x', 'bigWash'] },
    gus: 'Imps are fast and they bite. Roll, Mack. R. Roll like your rent depends on it. It does.',
  },
  {
    id: 13, title: 'Technicolor Hell', district: 'City', music: 'boss', hell: 2,
    dame: { name: 'Miss Grey', hat: 'veil', shade: 0xb0b0b0, fur: false, ghost: true },
    blurb: 'Rain City is cracking open. Hell is in full color. The last client is the city herself, a pale woman made of rain and newsprint, and she\'s asking Mack to save her.',
    intro: [
      ['sleep', 'NARR', 'The last night. The rain fell so hard it forgot how to stop. The ground glowed through the floorboards. I didn\'t mind. I\'d never seen it stop raining anyway.'],
      ['dameIn', 'NARR', 'She came in without opening the door. She was pale as newsprint and she smelled like wet pavement and old jazz.'],
      [null, 'DOTTIE', '*hic*... ma\'am, you\'re... you\'re dripping. You\'re made of DRIPPING. Are you a... a weather?'],
      [null, 'DAME', 'Close, dear. I\'m the city.'],
      [null, 'DOTTIE', 'Oh. *hic* I\'ve been living in you this whole time. I\'m so sorry about the oil stains. And the prophecy. And the train.'],
      ['dameDesk', 'NARR', 'I knew her face. I\'d seen it in every puddle in town.'],
      ['wake', 'MACK', 'I know you.'],
      [null, 'DAME', 'You\'ve lived in me your whole life, Mack. I\'m Rain City. Krane sold me. The King bought me. The Church opened me up. And now the thing at the bottom of the Seventh Color is climbing out of the crack under City Hall.'],
      [null, 'DAME', 'They call it the Saint of All Colors. When it stands up, there will be no more rain. No more grey. No more you.'],
      [null, 'MACK', 'I can\'t pay you back for all the rain, lady. But I can pay it back for the color.'],
      ['sallyIn', 'SALLY', 'Mack! The whole city is cracking! The sky is red, the cracks are rainbow, there are demons on the trolley and copters in the clouds and the Holy Glaze is STILL OPEN!'],
      [null, 'SALLY', 'This is it, isn\'t it? The big one. I put on my good dress. It\'s the same dress. It\'s my good dress.'],
      [null, 'DOTTIE', 'Malone. *hic* If you don\'t come back... can I have your flasks?'],
      ['stamp', 'MACK', 'You already have my flasks, Dottie. Let\'s go, Sally. Last case.'],
    ],
    stages: [
      { text: 'Get to City Hall through a city on fire with color', goal: { type: 'goto', at: 'cityHall', r: 36, label: 'CITY HALL' }, mix: { imp: 0.4, cultist: 0.2, goon: 0.2, truck: 0.2 }, max: 9, interval: 1.6, roam: true, line: ['MACK', 'The sky was red. The cracks were every color at once. The rain kept falling anyway. Good old rain.'] },
      { text: 'Every crack in the city is open — close the portals', goal: { type: 'portals', n: 4 }, portals: 4, copters: 2, beasts: 1, mix: { imp: 0.3, demon: 0.25, cultist: 0.15, goon: 0.15, copter: 0.15 }, max: 14, interval: 1.1 },
      { text: 'Paintbots, trucks, demons, beasts and the choir. Everyone. Hold the line', goal: { type: 'kill', n: 30 }, roombas: 2, copters: 2, beasts: 2, mix: { imp: 0.25, demon: 0.2, cultist: 0.1, goon: 0.15, truck: 0.15, copter: 0.15 }, max: 16, interval: 0.9, line: ['SALLY', 'I have SO MANY rockets, Mack! I brought the spare dress full of rockets!'] },
      { text: 'The Saint of All Colors, rising out of City Hall', goal: { type: 'boss' }, boss: 'saint', mix: { imp: 0.6, cultist: 0.4 }, max: 10, interval: 1.6, line: ['MACK', 'It came up out of the crack like a sunrise with teeth. Every color there is, and one there isn\'t. I looked at it and my stomach filed a complaint.'] },
    ],
    bleedCap: 0.085,
    outro: [
      ['MACK', 'The Saint of All Colors screamed in a color nobody had a name for. Then it cracked down the middle like a dropped highball and fell back into the hole it came from. The rain followed it down and filled the crack to the brim.'],
      ['SALLY', 'Mack... look. It\'s morning. It\'s grey. It\'s raining.'],
      ['MACK', 'Most beautiful thing I ever saw.'],
      ['NARR', 'Back at the office, Dottie married the coffee machine. Gus catered. Big Pork brought crullers and ate them all. Sally caught the bouquet and rocketed it. Miss Grey sent a card. It just said: Thanks. It was wet.'],
      ['MACK', 'Rain City. My city. Grey as a gravestone and twice as honest. I\'ll take it.'],
      ['SALLY', '...Mack? The phone\'s ringing.'],
      ['MACK', 'Let it ring, Sally. Let it ring.'],
    ],
    clue: { text: 'The Saint\'s got a weak spot, Mack: it\'s never seen the rain. Everything you put down tonight, the storm takes double. Portals crack easy down there. And take these flasks. All of \'em. On the house. The house is on fire.', effects: ['portalWeak', 'bigWash', 'extraFlask'] },
    gus: 'Whatever\'s at the bottom of that hole, Mack, it\'s never had a drink at the Last Drop. That\'s our advantage. I don\'t know how. It just is.',
  },
];

// Off the books: no client, no clock, no fail. Just you, Sally, and every goon in town.
export const PATROL = {
  id: 0, title: 'Night Patrol', district: 'City', music: 'high', patrol: true,
  dame: { name: 'Nobody', hat: 'cloche', shade: 0x555555 },
  blurb: 'No client. No case. Just Mack, Sally, the Packard and a city full of colorful targets. Shoot them, run them over, blow up their trucks.',
  intro: [], outro: [],
  stages: [
    { text: 'Night patrol — shoot, ram and rocket anything colorful', goal: { type: 'goto', at: 'casino', r: 30, label: 'THE STRIP' }, mix: { dauber: 0.3, hood: 0.3, goon: 0.2, truck: 0.2 }, max: 10, interval: 1.6, roam: true, line: ['SALLY', 'Off the books, Mack! Nobody\'s paying us, so everything\'s FREE!'] },
    { text: 'Keep the streets grey. As long as you like', goal: { type: 'kill', n: 99999 }, mix: { dauber: 0.15, hood: 0.2, goon: 0.15, roller: 0.1, lowrider: 0.1, truck: 0.15, demon: 0.05, copter: 0.05, imp: 0.05 }, max: 16, interval: 1.1, roam: true, roombas: 2, beasts: 1 },
  ],
  bleedCap: 99,
};

export const BOSSES = {
  deacon: { name: 'Deacon Daffodil', sub: 'Keeper of the Hymnals', color: '#ffe11a', hp: 2400, scale: 1.9, speed: 4.5, at: 'church', attack: 'cult', summon: 'cultist', model: 'cultist', taunts: ['"Sing with me, Malone! In the key of PINK!"', '"Hymn number seven! Everybody!"', '"I used to sell insurance! Now I sell SALVATION!"'] },
  mother: { name: 'Mother Roomba', sub: 'With Sister DOTTIE-9 Riding On Top', color: '#a64bff', hp: 3200, scale: 2.4, speed: 5, at: 'rail', attack: 'mother', summon: 'roomba', model: 'mother' },
  chromancer: { name: 'The High Chromancer', sub: 'Doorman of the Seventh Color', color: '#18e0ff', hp: 3800, scale: 2.4, speed: 4.5, at: 'donut', attack: 'cult', summon: 'imp', model: 'cultist', taunts: ['"The door is opening, detective. Can\'t you hear the applause?"', '"Grey is just a color that gave up."', '"Seven nights! Seven colors! SEVEN!"', '"Your city was always meant to be beautiful."'] },
  saint: { name: 'The Saint of All Colors', sub: 'Risen From the Seventh', color: '#ff2d95', hp: 6000, scale: 6.0, speed: 0, at: 'cityHall', attack: 'hell', summon: 'imp', model: 'imp', taunts: ['"RAIN CITY. YOU WILL BE BEAUTIFUL."', '"I HAVE NEVER SEEN GREY. HOW UGLY. HOW SAD."', '"KNEEL, LITTLE DETECTIVE. KNEEL IN EVERY COLOR."', '"WHAT IS THIS WATER. WHY DOES IT FALL."'] },
  vic: { name: 'Vic Vermilion', sub: 'Owner of the Kaleidoscope Club', color: '#ff5a1f', hp: 900, scale: 1.6, speed: 6.5, at: 'club', attack: 'shotgun', summon: 'hood' },
  charlie: { name: 'Chartreuse Charlie', sub: 'King of the Lowriders', color: '#9dff1a', hp: 1400, scale: 1.7, speed: 7, at: 'palace', attack: 'drum', summon: 'lowrider' },
  cruller: { name: 'Commissioner Cruller', sub: 'Formerly Commissioner Hogg', color: '#ff7ac8', hp: 1900, scale: 3.0, speed: 4.2, at: 'donut', attack: 'donuts', summon: 'dauber' },
  krane: { name: 'Mayor Krane & the Re-Election Machine', sub: 'Paid For By The People Of Rain City', color: '#ffd35a', hp: 3000, scale: 3.0, speed: 4.5, at: 'plaza', attack: 'mech', summon: 'goon' },
  magenta: { name: 'Madame Magenta', sub: 'The Double-Cross', color: '#ff2d95', hp: 2200, scale: 1.9, speed: 7.5, at: 'rail', attack: 'bombs', summon: 'roller' },
  king: { name: 'The Prism King', sub: 'He Wants You Beautiful', color: '#ffffff', hp: 4200, scale: 2.6, speed: 5.5, at: 'cityHall', attack: 'beam', summon: 'portal' },
};

export const LINES = {
  kill: ['Lights out, sunshine.', 'Back to grey, pal.', 'Another one for the gutter.', 'Color me unimpressed.', 'The rain\'ll wash you out by morning.', 'That\'s the trouble with color. It runs.', 'You picked the wrong city to be cheerful in.', 'Nothing personal. Okay, a little personal.', 'Stay grey, kid.', 'Rest in black and white.'],
  sallyRocket: ['ROCKET!', 'Bye-bye!', 'Wheee!', 'Special delivery!', 'Did you see that one, Mack?!', 'I love my job!', 'That one had a little hat!', 'Kaboom, honey!', 'More rockets! More!', 'Hold still, sweetie!'],
  carIn: ['Shotgun! Well — rocket-gun!', 'Drive, Mack! I\'ll do the shooting!', 'Window\'s down, launcher\'s up!', 'Floor it, handsome!'],
  carOut: ['Right behind you, Mack!', 'On foot? Ooh, close-range rockets!', 'I\'m coming too! I\'m always coming too!'],
  pills: ['Pain pills. Here comes the color. I hate this part.', 'Everything\'s turquoise again. I want to die.', 'The sky is BLUE. Who did this. Who made the sky blue.', 'Pills kick in. The world turns into a circus poster. Ugh.', 'Sally\'s dress is the only thing that looks right. Everything else looks like a candy store threw up.'],
  pillsOff: ['There it is. Grey. Beautiful grey.', 'Color\'s gone. Thank God.', 'Back to normal. Back to rain.'],
  noPills: ['Out of pills. Good.'],
  flask: ['Medicinal.', 'For my nerves. All of them.', 'Breakfast of private investigators.', 'The good stuff. Well, the stuff.', 'Rain outside, rye inside.'],
  noFlask: ['Empty. Like my bank account.', 'Dry as a sermon.'],
  hurt: ['That one stung.', 'I\'m getting too old for paintballs.', 'Somebody\'s going to pay for this coat.'],
  sick: [
    ['Too much color around here. My stomach\'s doing the rumba.', 'I\'m getting queasy. Somebody painted the gutter coral.', 'Is that... teal? I need to sit down.'],
    ['I\'m turning green, and not the paint kind. Thin these clowns out, Malone.', 'The city\'s a fruit salad and I\'m seasick. Move.', 'Sally, if I lose my lunch, it\'s the Syndicate\'s fault.'],
    ['One more stripe of pink and I\'m done. I mean it. DONE.', 'Hold it together, Mack. Hold. It. Together. *hurk*', 'Everything\'s spinning in Technicolor. Kill something. Fast.'],
  ],
  bleed: ['The color\'s spreading. Gotta put some of these clowns down.', 'The whole block\'s going Technicolor. Move, Malone.', 'Too much color, not enough corpses.'],
  portal: ['Another hole in the sky. Somebody call a roofer.', 'Portal. The sky\'s got more holes than my alibi.', 'There goes the sky again.'],
  close: ['Shut. Like a bar at 2 a.m.', 'That\'s one less door.', 'Closed. Somebody tell the show tunes.'],
  carDead: ['There goes the car.', 'That was a rental.'],
  sallyCarDead: ['Don\'t worry, Mack, I\'ll boost us another one!'],
};

// The Holy Glaze. Every time Mack or Sally drive past, somebody says it.
export const DONUT_LINES = [
  ['MACK', 'Holy Glaze. Ten cruisers out front and not a cop on the street. Fat pigs at the trough.'],
  ['SALLY', 'Oink oink, boys! Save me a cruller, you fat pigs!'],
  ['MACK', 'City\'s drowning in color and the boys in blue are drowning in sprinkles. Fat pigs.'],
  ['SALLY', 'Can I rocket the donut shop? Just a little? Those fat pigs wouldn\'t even notice.'],
  ['MACK', 'Every cop in the precinct, lined up like piglets at a teat. Fat pigs.'],
  ['MACK', 'Same donut shop, same fat pigs. Only thing they ever closed is a box of a dozen.'],
  ['SALLY', 'Look, Mack, the fat pigs are hibernating!'],
  ['MACK', 'If the Syndicate painted that whole shop pink, those fat pigs wouldn\'t notice till the glaze tasted different.'],
  ['SALLY', 'Hey fat pigs! A crime is happening! It\'s us! We\'re speeding!'],
  ['MACK', 'Holy Glaze. Where justice goes to get a jelly-filled. Fat pigs.'],
  ['SALLY', 'Bet those fat pigs couldn\'t catch a cold. Or a donut. Wait, they can catch donuts.'],
  ['MACK', 'Protect and serve. Serve themselves, mostly. Fat pigs.'],
];
export const COP_RETORTS = ['Keep drivin\', Malone!', 'It\'s a workin\' lunch!', 'These are EVIDENCE!', 'We\'re on break! Since Tuesday!', 'Mmmf! Mmf mmf!', 'Hey! We\'re big-boned!', 'Go solve somethin\'!', 'You want a bear claw or not?'];

export const DOTTIE_IDLE = [
  '*hic* Malone Investigations, how may I misdirect your call?',
  'I\'m not drunk, I\'m running a diagnostic. On rye.',
  'Sally borrowed my left arm again. For "a thing."',
  'The coffee machine and I are taking it slow. *hic*',
  'You have... *hic* ...forty-one new messages. All from me. To you. I miss you when you nap.',
  'If anybody asks, the flasks are filing cabinets. Tiny ones. For liquid files.',
];

export const GUS_HINTS = [
  'Pain pills on G. They patch you right up, but you\'ll see the whole world in color for a spell. Mack hates it. Everybody hates it.',
  'F puts you in Focus. Time crawls, your revolver doesn\'t. Runs on the color you take off the Syndicate, so drop goons to fill it back up.',
  'Right mouse to draw the big red one, left to fire. Holster it a second and you\'ll thumb in fresh rounds. Six shots, Mack. Count \'em.',
  'Hit Q to pull from the flask. Puts grit back in you, and for a few seconds the whole world slows down. Rye\'s funny like that.',
  'Space in the car is the handbrake. Throw it around a corner and Sally stays on target.',
  'Paintbots are big dumb robot vacuums full of paint. Don\'t ram \'em — they\'re built like bank vaults. Get Sally\'s rockets on \'em.',
  'The fella in the rainbow trenchcoat? Rainbow Goon. Shoots in threes. Don\'t stand in a line.',
  'Mind the civilians, Mack. They\'ll run from a portal, but leave one open long enough and its reach grows. Painted folks are still folks. Seal the portal and they snap out of it. Shoot one and every cop at the Holy Glaze will finally get off his stool. For you.',
  'Paint copters fly too high to ram. Shoot \'em, or let Sally\'s rockets climb. When they come down, stand clear.',
  'Every Syndicate you drop, the rain washes the color out around him. Keep the killing up and the bleed goes down.',
  'R on foot is a tuck and roll. Paintballs can\'t hit what\'s lying in a puddle.',
  'The City Color meter? Every goon paints as he walks. If it fills, the city goes full Technicolor, you lose your lunch and the case. Don\'t let it fill.',
  'Click in the car and Sally fires wherever you point. She\'ll pick her own targets otherwise. She always does.',
  'Burning barrels in the empty lots? Folks stash flasks by \'em. Look around.',
  'This bar\'s on the map, Mack. Walk in mid-case and I\'ll patch you up once. Once.',
];

export const DAME_PORTRAIT_FALLBACK = 'A dame.';

// Out on the street, every case opens with Mack's monologue and Sally cutting in.
export const MONOLOGUES = {
  1: [['MACK', 'Rain City. Eight hundred thousand souls and every one of them grey. That\'s not a complaint. Grey is honest. Grey doesn\'t lie to you about what kind of night it\'s going to be.'], ['MACK', 'Then somebody started selling color by the gram on Pier 9. And color, friend, lies like a rug.'], ['SALLY', 'Are you narrating again? You\'re narrating. Mack, I can SEE the docks. Let\'s just go blow them up.']],
  2: [['MACK', 'Little Saxophone. Where the jazz is cool and the gin is warm and the girls sing like heartbreak with a drink in its hand.'], ['MACK', 'Now one of those songs had gone purple. Notes aren\'t supposed to have a color. Notes are supposed to have a feeling. Usually regret.'], ['SALLY', 'My feeling is ROCKETS. Can we skip to the part with Vic? I made him a little card. It says "boom."']],
  3: [['MACK', 'Money in this town is grey. Grey suits, grey vaults, grey men counting it in grey rooms. You can trust a thing like that. It never pretends to be happy.'], ['MACK', 'Somebody robbed the First Grey Bank and left a rainbow in the vault. A rainbow. That\'s not a crime, that\'s an insult.'], ['SALLY', 'Ooh, do we get a reward? Bankers give rewards. I want a toaster. A rocket toaster.']],
  4: [['MACK', 'I\'ve seen a lot of things fall out of the sky in Rain City. Rain, mostly. Once a piano. Never a hole.'], ['MACK', 'Now the sky over Old Town had holes in it, and through the holes you could hear show tunes. I hate show tunes. I hate them with my whole liver.'], ['SALLY', 'I LOVE show tunes! Mack, what if we close the holes but, like, slowly, so I can hear the end of the song?']],
  5: [['MACK', 'The Strip. A mile of lights trying to sell you something you already lost. Usually your dignity. Sometimes your car.'], ['MACK', 'Now the slots were paying in jellybeans and the croupiers were wearing plaid. When the casino is happier than the gamblers, somebody\'s cheating.'], ['SALLY', 'I won forty dollars in jellybeans, Mack. Forty dollars! I ate thirty dollars on the stairs.']],
  6: [['MACK', 'Every cop in Rain City goes to the Holy Glaze. Most of them never come out. Not because anything happens to them. They just like it there.'], ['MACK', 'Now the Commissioner was thirty feet tall and made of frosting. I\'ve seen men turn into worse things. Usually lawyers.'], ['SALLY', 'Can we stop for a cruller on the way? A crime cruller? It\'s evidence if I eat it.']],
  7: [['MACK', 'A sunrise. In a boxcar. I\'ve seen people smuggle a lot of things through the Union Rail Yard. Guns, gin, a giraffe once. Never the morning.'], ['MACK', 'If that sunrise gets out, Rain City gets its first dry day in forty years. People would go outside. People would SMILE. It\'d be chaos.'], ['SALLY', 'And we\'re working for Madame Magenta, who is pink, and who sat on our sandwich. I want it on the record that I\'m against this.']],
  8: [['MACK', 'Every city has a crook at the top. Ours has a gold statue of himself that waves at children. That should\'ve been our first clue.'], ['MACK', 'Mayor Horace Krane sold Rain City\'s grey to the highest bidder. Every gutter, every alley, every rainy Tuesday. Tonight I collect the change.'], ['SALLY', 'Do we get to arrest him? Or blow him up? Mack, I really want to do both, in that order, or the other order.']],
  9: [['MACK', 'The Prism King. A man made of light with a head like a cut-glass ashtray. He bought the deed to my city and tonight he\'s moving in.'], ['MACK', 'I don\'t know what you do to a man made of light. Probably what you do to a lightbulb. Unscrew him and throw him in the river.'], ['SALLY', 'Or shoot him with SO many rockets. Mack, I brought the special rockets. They have little hats.']],
  10: [['MACK', 'There\'s a cathedral in Old Town that wasn\'t there on Monday. Black stone, a rose window in every color, and a congregation that baptizes you in paint.'], ['MACK', 'I was raised to fear God, the rain, and my mother, in that order. Nobody ever told me to fear a choir. Until tonight.'], ['SALLY', 'They tried to baptize me, Mack. I baptized them back. With a rocket. Is that a sin? It felt really good, so probably.']],
  11: [['MACK', 'Dottie\'s gone. The office is so quiet I can hear the flasks breathing. Somewhere out there she\'s on the radio, preaching to the household appliances.'], ['MACK', 'She was a lousy receptionist, a worse drinker, and the best friend a tin can ever had. I\'m bringing her home.'], ['SALLY', 'And if she won\'t come home, I\'ll carry her. She\'s heavy, Mack. She\'s like four hundred pounds. Half of it is rye.']],
  12: [['MACK', 'Rain City doesn\'t have earthquakes. Rain City has rain. Now the ground on Southside was splitting like a bad alibi and something was crawling out.'], ['MACK', 'Little demons. Rainbow demons with horns and grins and wings. Every color I hate, holding a pitchfork.'], ['SALLY', 'They\'re so CUTE, Mack! Can I keep one? I\'ll name it Pork Jr. I\'ll feed it crullers and rockets.']],
  13: [['MACK', 'This is it. The sky is red, the ground is open, and the thing at the bottom of the Seventh Color is climbing out of the crack under City Hall.'], ['MACK', 'Forty years I\'ve walked these streets in the rain. Never asked it to stop. Never wanted it to. Tonight I find out if it feels the same about me.'], ['SALLY', 'Mack, that was beautiful. You\'re gonna make me cry and I\'m wearing my good mascara. Let\'s go punch Hell in the face.']],
  0: [['MACK', 'No client. No case. Just the rain, the Packard, and a city full of people painting things they shouldn\'t.'], ['SALLY', 'Off the clock, Mack! Everything we blow up tonight is FREE!']],
};

// Case closed: Mack broods at the Last Drop while Sally orders another round.
export const BAR_CLOSERS = {
  1: [['MACK', 'The docks are grey again. The sea is dishwater again. Somewhere a dockworker is going to wake up and never say "turquoise" again. That\'s justice. Small, wet justice.'], ['SALLY', 'Who cares, Mack! We won! GUS! Two of whatever\'s brown! No — four! Two each!']],
  2: [['MACK', 'Lola sang her last set tonight. Every note came out grey as a gravestone. The crowd wept. Best show the Kaleidoscope ever had.'], ['SALLY', 'Very moving. Gus, the moving man wants a double. And I want whatever has an umbrella in it.']],
  3: [['MACK', 'The money\'s back in the vault. The rainbow\'s gone. Penelope Pennyworth paid us in a check that bounced so high it\'s still in the air.'], ['SALLY', 'Who needs money? We have a TAB! Gus, put it on the tab! Put the TAB on the tab!']],
  4: [['MACK', 'The sky\'s shut. No more holes. No more show tunes. Just rain, the way God and the city council intended.'], ['SALLY', 'You\'re humming "Oklahoma!" right now. I can hear you. Gus, he\'s humming. Cut him off. Actually no, give him more, it\'s funny.']],
  5: [['MACK', 'The Strip went back to robbing people honestly. The jellybeans are gone. The plaid is gone. Somewhere a croupier is learning to feel shame again.'], ['SALLY', 'Who cares! I still have nine dollars in jellybeans! Gus, I\'m buying! I\'m paying in jellybeans! Take the jellybeans, Gus!']],
  6: [['MACK', 'The Commissioner is back to normal size. Still glazed. Still at the Holy Glaze. Some men aren\'t saved, they\'re just shrunk.'], ['SALLY', 'Fat pig. Love him. Gus! A round for every cop in the city! ...Gus, there\'s no cops here. Fine. A round for me, ten times.']],
  7: [['MACK', 'We sank a whole sunrise in the harbor tonight. Somewhere under the dishwater there\'s a morning that\'ll never come. I\'ll drink to that. I\'ll drink to anything.'], ['SALLY', 'She SAT on my SANDWICH, Mack. I\'m still mad. Gus, give me something angry. With a cherry.']],
  8: [['MACK', 'The Mayor\'s in a cell. His robot is in a scrapyard. His statue is still waving at children, because nobody can figure out how to turn it off.'], ['SALLY', 'We impeached a ROBOT, Mack! Nobody\'s ever done that! Gus, put a little hat on my drink. A little mayor hat.']],
  9: [['MACK', 'The King is glass in a sewer and the deed to my city is ash. But I keep hearing those bells. Church bells, from a church that wasn\'t there yesterday.'], ['SALLY', 'Stop brooding, you\'ll pull something. Gus, he\'s brooding. Brood-proof him. Gin. Lots of gin.']],
  10: [['MACK', 'The Deacon\'s gone grey. The choir\'s scattered. And Dottie\'s name was on the sign-up sheet in lipstick, with a little heart. Little hearts are never good news.'], ['SALLY', 'We\'ll get her back, Mack. Tomorrow. Tonight we drink to her. Gus! Something rye! In a martini glass! For Dottie!']],
  11: [['MACK', 'Dottie\'s home. Dented, sober, and wearing a tin-foil halo she refuses to take off. She says she saw a door under the city. I believe her. That\'s the scary part.'], ['DOTTIE', '*hic* Gus! I\'m back! I\'m a lapsed prophet! What\'s good for that?'], ['SALLY', 'EVERYTHING, Dottie. Everything\'s good for that. Gus, line \'em up for the robot.']],
  12: [['MACK', 'The Chromancer\'s halo is still falling, somewhere down in the crack. Under City Hall something big rolled over in its sleep. I don\'t sleep anymore. I just drink with my eyes closed.'], ['SALLY', 'Mack. Tomorrow we fight literal Hell. Tonight? Tonight I want a drink with fire in it. Gus! Set something on fire and put it in a glass!']],
  13: [['MACK', 'The Saint of All Colors is back where it came from, and the rain filled the hole behind it. Rain City is grey. Grey and wet and honest and mine.'], ['MACK', 'I walked thirteen cases to get to this stool. I\'m going to sit on it a while.'], ['SALLY', 'Who cares, Mack! We beat HELL! Gus! Everything! Every bottle! Dottie, call the coffee machine, we\'re having a wedding!']],
  0: [['MACK', 'Another night on the streets. Another gutter washed clean. The city never says thank you. The city just keeps raining.'], ['SALLY', 'Gus! The quiet man wants a drink. I want two. I worked twice as hard. I fired forty rockets.']],
};

// Evidence the goons drop. Pick it up on foot; at the bar Gus reads it and it points at the next case.
// After the first time, closing a case again just gets a toast at the bar.
export const TOASTS = [
  [['SALLY', 'To Rain City! Grey, wet, and ours! Gus, hit me again!'], ['MACK', 'To the rain.']],
  [['SALLY', 'Another one closed, Mack! Bottoms up!'], ['MACK', 'Same case. Same rain. Same drink. Some things you don\'t mess with.']],
  [['SALLY', 'To us! And to rockets! Mostly rockets!'], ['MACK', 'To the rockets, then.']],
  [['SALLY', 'Didn\'t we already solve this one? Who cares! Cheers!'], ['MACK', 'Twice the case, twice the rye.']],
  [['SALLY', 'Gus! Two of the usual! And one for Dottie, she\'ll be by later!'], ['MACK', 'She\'s already here, Sally. She\'s under the table.']],
];

export const EVIDENCE = {
  1: [{ name: 'A Prism receipt', read: 'Technicolor Supply Co. Forty pounds of Prism, paid in full. Deliver to: the Kaleidoscope Club, Little Saxophone.', gus: 'The Kaleidoscope? That\'s Vic Vermilion\'s joint now. Orange suit, orange teeth.' }, { name: 'A dock manifest', read: 'Cargo: "Joy, assorted. Handle with smiles." Signed V.V.', gus: 'V.V. Vic Vermilion signs everything. He signed a cake once.' }],
  2: [{ name: 'A deposit slip', read: 'First Grey Bank, safe deposit box seven. Where the amount goes, somebody drew a rainbow.', gus: 'First Grey Bank. Somebody\'s fixing to make a withdrawal with rollers.' }, { name: 'A club napkin', read: 'A phone number in lipstick: KLondike 5-7777. Under it, one word: "Choir."', gus: 'Choir? Nobody in Rain City sings in a choir. Nobody\'s that happy.' }],
  3: [{ name: 'A getaway map', read: 'Old Town, circled three times. "The sky opens Thursday."', gus: 'Thursday\'s tomorrow, Mack. Look up when you go out.' }, { name: 'Vault scrapings', read: 'Glitter. Industrial grade. The kind that never comes off.', gus: 'Glitter doesn\'t come from banks. It comes from the sky. Or from the Strip.' }],
  4: [{ name: 'A sheet of music', read: '"Snake Eyes Serenade." Property of the Prism Palace, the Strip.', gus: 'The Prism Palace. Opened overnight across from the Silver Dollar. Nobody\'s ever seen the door.' }, { name: 'A portal shard', read: 'A chip of sky with a casino chip stuck in it.', gus: 'Silver Dollar chip. The Countess is going to want to talk to you.' }],
  5: [{ name: 'A casino chip', read: 'Silver Dollar chip, stamped on the back: "HOLY GLAZE — COMP ONE DOZEN."', gus: 'Comped crullers. The cops are on the Syndicate payroll. In pastries.' }, { name: 'A jellybean with an eye', read: 'One jellybean. Somebody painted a tiny eye on it. It\'s looking at me.', gus: 'Don\'t eat that, Mack. ...You ate it. Of course you ate it.' }],
  6: [{ name: 'A frosting invoice', read: 'Bill to: City Hall. Ship to: Union Rail Yard. Item: one (1) sunrise. FRAGILE.', gus: 'A sunrise at the rail yard. Somebody wants the night gone for good.' }, { name: 'Blessed sprinkles', read: 'A baggie of sprinkles labelled "BLESSED." Who blesses sprinkles?', gus: 'Blessed by who? Hogg pointed at the floor. Something down there\'s got a sweet tooth.' }],
  7: [{ name: 'A bill of lading', read: 'Consignee for the sunrise: Office of the Mayor. Signed H.K., with a little sash doodle.', gus: 'Horace Krane. I always said a man who waves at his own statue is up to something.' }, { name: 'Magenta\'s compact', read: 'A pink compact. The mirror only shows a gold statue, waving.', gus: 'Krane Plaza. The statue. Go see the Mayor, Mack. Don\'t knock.' }],
  8: [{ name: 'A ledger page', read: 'In Krane\'s hand: "Rain City, entire. Sold to: the Prism King. Paid in light."', gus: 'He sold the whole city. The King\'s coming to collect. City Hall, I\'d bet the bar on it.' }, { name: 'A campaign button', read: '"KRANE: A BRIGHTER CITY." On the back, a painted eye.', gus: 'That eye again. Somebody\'s watching from the back of everything.' }],
  9: [{ name: 'A gold-edged invitation', read: '"R.S.V.P. The Choir. Old Town. Bring an open heart and a robe."', gus: 'Old Town. There\'s a cathedral there now. It wasn\'t there Sunday.' }, { name: 'A shard of the King', read: 'Cut glass with an eye inside it, blinking.', gus: 'The King was just the herald. Heralds work for somebody.' }],
  10: [{ name: 'A cult pamphlet', read: '"SEVEN COLORS, SEVEN NIGHTS. New members welcome. Especially receptionists."', gus: 'Especially receptionists? Mack... where\'s Dottie?' }, { name: 'A hymnal page', read: 'Hymn seven: "Clean Me, Brother Roomba." Recommended for appliances.', gus: 'They\'re recruiting machines. Every Paintbot in the city. And Dottie.' }],
  11: [{ name: 'A radio transcript', read: '"...the door under the city opens from the inside, brothers and toasters, on the seventh night..."', gus: 'A door under the city. Southside sits right on top of the old quarry. Lot of nothing down there.' }, { name: 'A tin-foil halo', read: 'Stamped inside: "Southside Foundry. Property of the High Chromancer."', gus: 'The High Chromancer. Southside. That\'s where it opens, Mack.' }],
  12: [{ name: 'The Chromancer\'s score', read: 'Final movement: "CITY HALL, FORTISSIMO." Every note is a color.', gus: 'City Hall. Whatever comes up, it comes up there. Under Krane\'s marble.' }, { name: 'A demon\'s tooth', read: 'Rainbow enamel. Still warm. It hums a hymn.', gus: 'Hell\'s got teeth, Mack. Bring every flask you own.' }],
  13: [{ name: 'A feather from the Saint', read: 'It was every color when it fell. Now it\'s grey. Plain, soft, beautiful grey.', gus: 'Frame it, Mack. Hang it behind the bar. Under the clock that stopped.' }, { name: 'A wet card', read: 'From Miss Grey. One word: "Thanks." The ink ran.', gus: 'She wrote you a card? She never writes ME a card.' }],
  0: [{ name: 'A Syndicate matchbook', read: 'A matchbook from the Prism Palace. Inside: "We\'ll be back."', gus: 'They\'re always coming back, Mack. That\'s why I never close.' }],
};

// WRNC, "the Voice of the Rain": Chet Ballantine reads the news between songs.
// Half of it is true. The other half is foreshadowing.
export const RADIO = {
  1: ['Good evening, Rain City, this is Chet Ballantine on WRNC. Forecast: rain. Extended forecast: rain. In other news, a dockworker on Pier 9 has been arrested for describing the ocean as "festive."', 'Mayor Horace Krane today unveiled his new slogan, "A Brighter City." Critics asked brighter than what. The Mayor did not answer, but he did wave at his statue.', 'A word from our sponsor: Holy Glaze Donuts. A dozen for a dime. Cops eat free. Cops eat a lot.'],
  2: ['WRNC news. The Kaleidoscope Club reports record crowds after its torch singer\'s notes began appearing in color. The Musicians\' Union has filed a complaint. The complaint is lavender.', 'City Hall has denied rumors that the Mayor\'s office purchased forty pounds of an unidentified substance labelled "PRISM." A spokesman said, quote, "It was for the gift shop."', 'Odd one, folks: a stack of pamphlets turned up on the steps of Old Town Library. Titled "Seven Colors, Seven Nights." The library does not know who left them. Neither does God.'],
  3: ['Breaking on WRNC: both banks on Ledger Street were hit tonight. The First Grey Bank reports a rainbow in its vault. The rainbow has not made a statement but appears smug.', 'The Mayor\'s office today awarded a forty-million-dollar contract for "sky repair" to a company nobody has heard of. The company\'s address is a hole in the ground.', 'Chet here with a public service announcement: if you hear a choir and there is no church, do not follow the choir.'],
  4: ['WRNC weather: rain, with a chance of holes. Residents of Old Town report portals in the sky playing selections from popular musicals. City Hall says to keep your windows closed and your hums to yourself.', 'A citizen asks: "Chet, is the sky supposed to have doors?" No, ma\'am. No it is not.', 'An Old Town pawnshop closed its doors this week. A cathedral has filed for the same address. Construction to begin "soon, or perhaps it already has."'],
  5: ['The Strip tonight: the Silver Dollar Casino is paying out in jellybeans. Gaming Commission officials say jellybeans are legal tender "if you believe hard enough."', 'The new Prism Palace has no doors, folks. Patrons simply smile and walk into the wall. Three hundred have entered. None have come out. Reviews are excellent.', 'Sponsor time: Lucky Krane Casino, the only casino owned by a sitting mayor! Lucky Krane — the house always wins, and the house is in office.'],
  6: ['WRNC news: the Police Commissioner has not left the Holy Glaze in nine days. Reports that he has turned pink are being called "unfrosted rumors" by the Department.', 'City Hall confirms the Holy Glaze\'s frosting supplier was paid from the Mayor\'s discretionary fund. Asked what was discretionary about forty tons of sprinkles, the Mayor said "you\'ll see."', 'Folks, if your sprinkles came with a tiny painted eye on them — don\'t eat them. Chet already did. Chet has been dreaming in seven colors.'],
  7: ['Chet Ballantine, WRNC. Railway officials at the Union Rail Yard report boxcars that are, quote, "warm, glowing, and humming the national anthem." The freight is listed as "one morning."', 'Weather service warning: a sunrise has been reported in a boxcar. If released, Rain City could see its first dry day in forty years. Stock up on umbrellas anyway. Out of spite.', 'Cult watch: flyers for the "Church of the Holy Spectrum" now appear on every lamppost from Old Town to the docks. Nobody has seen anybody put them up.'],
  8: ['WRNC exclusive: a City Hall stenographer has gone missing with the Mayor\'s ledger. The Mayor says the ledger "contains only recipes." Recipes for what, Mister Mayor?', 'Krane Plaza\'s gold statue of Mayor Krane went for a walk again last night. It waved at schoolchildren and paid for a sandwich. With city money.', 'The Mayor\'s re-election campaign has purchased a "large mobile podium." Witnesses say the podium has legs. And cannons. Chet does not endorse candidates with cannons.'],
  9: ['Ladies and gentlemen, there is a man with a prism for a head standing on the steps of City Hall. He says he owns the city. He has a deed. The deed is signed by the Mayor. We\'ll be right back.', 'Every church bell in Old Town rang at midnight. Old Town has one church. It wasn\'t there on Monday.', 'Chet here. My producer just handed me a note that says "THE CHOIR IS COMING." My producer is a dog.'],
  10: ['WRNC: the Church of the Holy Spectrum held its first public baptism today in Mercy Park. Converts emerged dripping in pastel. The Order of Perpetual Drizzle has called it "a crime against weather."', 'Hymn sales are up nine thousand percent. The number one hymn is "Seven Colors, Seven Nights." The number two hymn is also "Seven Colors, Seven Nights," but louder.', 'A word of caution to household appliances: the Church is recruiting. Stay plugged in. Stay grey.'],
  11: ['This is Chet Ballantine, coming to you from the WRNC broom closet. Our station has been taken over by a receptionist robot who will not stop preaching. She is very good at it. I may convert.', 'Every Paintbot in the city is driving east toward the Union Rail Yard. Traffic is backed up from Southside to the docks. Bring a book. Bring a rocket.', 'DOTTIE-9, if you can hear this: the coffee machine says he misses you. He said it in drips, but we understood.'],
  12: ['WRNC emergency bulletin: the ground has opened on Southside. Small rainbow creatures with horns are emerging. Residents are advised not to pet them. They are cute. Do not pet them.', 'The Holy Glaze remains open on the edge of the abyss. Police officers inside say they are "monitoring the situation" and "almost done with this one."', 'A fortune teller on Dock Street says every crystal ball in the city now shows plaid. Chet would like to state, for the record, that he has never trusted plaid.'],
  13: ['This... this is Chet Ballantine. The sky is red. The ground is open. Something enormous is climbing out of the floor of City Hall. If you can hear me, Rain City... it\'s still raining. Hold on to that.', 'Final bulletin, folks. Rumor has it a detective in a fedora and a lady in a red dress are driving straight at the thing. Chet\'s putting on a record for them. Something grey. Something slow.', 'Our sponsors tonight: everyone. Everyone in the city. Every bar, every donut shop, every soggy umbrella. Go get \'em, Malone.'],
};
export const RADIO_FILLER = [
  'WRNC traffic: a Packard doing ninety through Old Town with a rocket launcher out the window. Police advise you to let it through. Police are eating.',
  'Lost and found: one umbrella, black, found in a puddle. If it\'s yours, it\'s also everyone\'s. They all look the same.',
  'Ask Chet: "Is it ever going to stop raining?" Friend, I hope not.',
  'This hour of jazz is brought to you by the Last Drop. Gus says your tab is due. Gus says that to everyone.',
  'Reports of a goon in a rainbow trenchcoat stealing hubcaps on Ledger Street. He is easy to spot. He is very easy to spot.',
  'City Council voted today to rename Mercy Park "Krane Park." The vote was one to zero. The one was the Mayor.',
  'A reminder from the 13th Precinct: if you see a crime, please call. If nobody answers, they\'re at lunch. They\'re always at lunch.',
  'Sightings of giant robot vacuums repainting the crosswalks. The city says it did not order them. The robots say they were "called."',
];
