// The case files. Every case happens in the same rotten city, every case is
// louder and stranger than the last. Intro scenes play in Malone's office:
// he's asleep, a dame checks in with Dottie (the drunk robot receptionist),
// Sally kicks the door in, and they take the case.

export const CAST = {
  MACK: { name: 'Mack Malone', cls: 'mack' },
  SALLY: { name: 'Crazy Sally', cls: 'sally' },
  DOTTIE: { name: 'DOTTIE-9', cls: 'dottie' },
  GUS: { name: 'Gus', cls: 'gus' },
  COP: { name: 'Cop', cls: 'cop' },
  PORK: { name: 'Big Pork', cls: 'cop' },
  NARR: { name: '', cls: 'narr' },
};

// stage goal types: kill (any gang), portals (close the portals this stage opens), boss
export const CASES = [
  {
    id: 1, title: 'The Blue Period', district: 'The Docks', music: 'low',
    dame: { name: 'Mrs. Edna Pruitt', hat: 'cloche', shade: 0x6a6460, fur: false },
    blurb: 'A dockworker came home off the night shift and called the sea "blue." In this town the sea is the color of dishwater, and that\'s how we like it.',
    intro: [
      ['sleep', 'NARR', 'Rain City. 3 a.m. The rain had been falling so long it had seniority.'],
      [null, 'MACK', 'Zzz... no, officer... the flask was already empty when I got here... zzz...'],
      ['dameIn', 'NARR', 'She came in out of the rain like a bad idea with good shoes.'],
      [null, 'DOTTIE', '*hic* Malone Investigations. We find what you lost and drink what you didn\'t. Take a number. The number is... fourteen? *hic* Everything is fourteen tonight.'],
      [null, 'DAME', 'I need to see the detective. It\'s my husband, Walt. Thirty years on the docks.'],
      [null, 'DOTTIE', 'He\'s in a meeting. *hic* With the inside of his eyelids. I\'ll... I\'ll buzz him. BZZZT. That was me. I\'m the buzzer.'],
      ['dameDesk', 'NARR', 'Dottie rolled into the door frame twice before she found the right one.'],
      ['wake', 'MACK', 'Wha— who let the daylight in? Oh. It\'s just a dame. Sit down, lady. Mind the flasks.'],
      [null, 'DAME', 'Walt came home last night and said the sea was... blue, Mr. Malone. Not grey. BLUE. He won\'t stop saying "turquoise."'],
      [null, 'MACK', 'Turquoise. In my city. That\'s not a word, that\'s a crime.'],
      ['sallyIn', 'SALLY', 'Mack! There\'s kids down on Pier 9 selling something called PRISM! One whiff and you see colors! I already loaded the rockets!'],
      [null, 'MACK', 'Sally. You were supposed to knock.'],
      [null, 'SALLY', 'I did knock. With my boot. Are we taking it? Say we\'re taking it.'],
      ['stamp', 'MACK', 'We\'re taking it. Dottie, hold my calls.'],
      [null, 'DOTTIE', '*hic* I\'m holding all of them. In my heart.'],
    ],
    stages: [
      { text: 'Meet Big Pork at the Holy Glaze — he owes Sally a favor', goal: { type: 'goto', at: 'donut', r: 30, label: 'BIG PORK', arrive: [['PORK', '*chew* Malone. Sally. You didn\'t see me. I\'m a cop. I\'m eating. Those are the same thing.'], ['PORK', 'Kids on Pier 9 are pushing Prism. One sniff and you see colors. The Docks, Malone. And next time bring a cruller.'], ['MACK', 'Thanks, Pork. Fat pig.'], ['PORK', 'I heard that! ...It\'s fair.']] }, mix: {}, max: 0, interval: 9, line: ['SALLY', 'Big Pork! Best snitch in the 13th. Follow the red arrows, Mack — or hit Z and the Packard comes to you!'] },
      { text: 'Get down to the Docks', goal: { type: 'goto', at: 'docks', r: 40, label: 'PIER 9' }, mix: {}, max: 0, interval: 9 },
      { text: 'Ice the Prism pushers tagging the Docks', goal: { type: 'kill', n: 10 }, mix: { dauber: 1 }, max: 6, interval: 2.4, line: ['MACK', 'Daubers. Spray cans full of color. They paint, I erase. That\'s the whole job.'] },
      { text: 'They brought guns to a paint fight — clean up the crew', goal: { type: 'kill', n: 8 }, mix: { dauber: 0.5, hood: 0.5 }, max: 7, interval: 2.2, line: ['SALLY', 'Ooh, these ones shoot back! Paintballs! Mack, they\'re SHOOTING COLORS AT US!'] },
    ],
    bleedCap: 0.2,
    outro: [
      ['MACK', 'The docks went back to grey. The sea went back to dishwater. Walt went back to complaining. That\'s what I call a happy ending.'],
      ['SALLY', 'One of them had a business card. "The Technicolor Syndicate — We Put the Color in Your Cheeks." Fancy.'],
      ['MACK', 'Syndicate means organized. Organized means somebody\'s at the top. And somebody at the top means I\'m going to need a bigger flask.'],
    ],
    clue: null,
    gus: 'First night on the Prism case? Sally does the shooting from the car — you just drive. And you hit E to get out. Most fellas forget that part.',
  },
  {
    id: 2, title: 'Purple Rain Man', district: 'Little Saxophone', music: 'low',
    dame: { name: 'Lola LaRue', hat: 'veil', shade: 0x2a2a2e, fur: true },
    blurb: 'A torch singer at the Kaleidoscope Club sang a blue note, and it came out actually blue. Now the horn section is lavender.',
    intro: [
      ['sleep', 'NARR', 'Two nights later. The rain had a cousin in from out of town, and they were both falling on my roof.'],
      ['dameIn', 'NARR', 'She walked in like a saxophone solo — slow, low, and somebody was going to get hurt.'],
      [null, 'DOTTIE', 'Welcome to Malone Investigations, I am DOTTIE-9 and I have had *hic* nine. Hence the name.'],
      [null, 'DAME', 'Lola LaRue. I sing at the Kaleidoscope. Tell your boss a lady\'s voice turned purple.'],
      [null, 'DOTTIE', 'Turned purple? Honey, I once turned the coffee machine on and it turned ME on. We\'re engaged now. *hic*'],
      ['dameDesk', 'NARR', 'The coffee machine said nothing. It never does. That\'s how you know it\'s serious.'],
      ['wake', 'MACK', 'Lola LaRue. I\'ve heard you sing. Well — I\'ve heard about it from a guy who heard you sing.'],
      [null, 'DAME', 'Last Tuesday I hit a blue note and it came out BLUE, Malone. It floated over the crowd like a jellyfish. The new owner, Vic Vermilion, says it\'s good for business.'],
      [null, 'MACK', 'Notes are supposed to be heard, not seen. Somebody\'s mixing Prism into the gin.'],
      ['sallyIn', 'SALLY', 'Mack! Mack! The whole of Little Saxophone is going plaid! Vic Vermilion\'s got a guy painting the street lamps!'],
      [null, 'SALLY', 'Also I brought you a sandwich but I ate it on the stairs.'],
      ['stamp', 'MACK', 'Get the car. We\'re going to go see a man about an orange.'],
      [null, 'DOTTIE', 'I\'ll keep the seat warm. *hic* I\'ll keep ALL the seats warm. My battery runs hot.'],
    ],
    stages: [
      { text: 'Clear the Syndicate out of Little Saxophone', goal: { type: 'kill', n: 14 }, mix: { dauber: 0.5, hood: 0.5 }, max: 8, interval: 2.0, line: ['MACK', 'Little Saxophone. Where the jazz is cool, the gin is warm, and tonight the street is turning orange.'] },
      { text: 'Paintbots! Scrap the giant robot vacuums repainting Little Saxophone', goal: { type: 'roombas', n: 2 }, roombas: 2, mix: { hood: 0.5, dauber: 0.5 }, max: 6, interval: 2.4, line: ['SALLY', 'Mack! Giant robot vacuums! They\'re not sucking up dirt, they\'re SPITTING OUT PAINT! Dottie\'s gonna want to date one!'] },
      { text: 'Vic Vermilion is out front of the Kaleidoscope Club — put him down', goal: { type: 'boss' }, boss: 'vic', mix: { hood: 1 }, max: 4, interval: 3, line: ['SALLY', 'There he is! Orange suit, orange hat, orange personality! Can I rocket him? I\'m rocketing him.'] },
    ],
    bleedCap: 0.22,
    outro: [
      ['MACK', 'Vic Vermilion went down like the last round at closing time. The color ran out of him and into the gutter.'],
      ['SALLY', 'He said something before he went grey. "The money\'s already in the vault." What vault, Mack?'],
      ['MACK', 'In this town? There\'s only one vault worth saying it like that.'],
    ],
    clue: { text: 'Vic wears paint-thinner cologne. Real flammable. Tell Sally to aim high — her rockets\'ll hit him twice as hard.', effects: ['rocket2x'] },
    gus: 'Vic Vermilion keeps a crew of Hoods around him. Kill the Hoods and he\'s just a big orange man shouting.',
  },
  {
    id: 3, title: 'The Vault of Many Colors', district: 'Financial District', music: 'high',
    dame: { name: 'Penelope Pennyworth', hat: 'wide', shade: 0x8a8580, fur: true },
    blurb: 'Somebody robbed the First Grey Bank and left something behind in the vault: a rainbow. It\'s mocking the tellers.',
    intro: [
      ['sleep', 'NARR', 'Thursday. The rain was coming down so hard the pigeons had filed for unemployment.'],
      ['dameIn', 'NARR', 'She had old money and new problems. The money was quieter.'],
      [null, 'DAME', 'I am Penelope Pennyworth, of the Pennyworth Pennyworths. I require a detective. A cheap one.'],
      [null, 'DOTTIE', 'Our rates are very reasonable. Fifty a day plus expenses. Expenses are mostly... *hic* ...flasks.'],
      [null, 'DAME', 'Is that a flask in your chest compartment?'],
      [null, 'DOTTIE', 'It\'s a heart. Shaped like a flask. *hic* Full like a flask.'],
      ['dameDesk', 'NARR', 'Malone was awake this time. Mostly. Enough to count the zeros on her bracelet.'],
      ['wake', 'MACK', 'A Pennyworth in my office. Either you\'re lost or the money is.'],
      [null, 'DAME', 'Both banks on Ledger Street were robbed. The gold is gone. And in its place, in the First Grey vault, there is a RAINBOW. It hums. It has opinions. It called my father "a beige little man."'],
      [null, 'MACK', 'Prism needs money. Money needs a bank. Somebody\'s financing a revolution in a dress shop.'],
      ['sallyIn', 'SALLY', 'Mack, they\'re hitting the banks RIGHT NOW! Rollers! Big guys with paint rollers! They\'re painting the Mercantile Trust MAUVE!'],
      [null, 'DAME', 'Not mauve. Anything but mauve.'],
      ['stamp', 'MACK', 'Sally, warm up the car. Miss Pennyworth — you\'ll want to wait here. Dottie will fix you a drink.'],
      [null, 'DOTTIE', 'I only know one drink. It\'s called "the Whole Bottle." *hic*'],
    ],
    stages: [
      { text: 'Stop the heist crews hitting the banks', goal: { type: 'kill', n: 16 }, mix: { hood: 0.5, dauber: 0.3, roller: 0.2 }, max: 9, interval: 1.8, line: ['MACK', 'Rollers. Big men with big rollers and a head full of color. Let Sally soften them up.'] },
      { text: 'The getaway: Rollers and Rainbow Goons repainting Ledger Street', goal: { type: 'kill', n: 8 }, mix: { roller: 0.4, hood: 0.3, goon: 0.3 }, max: 8, interval: 1.8, line: ['SALLY', 'Mack, they\'re painting the street into a RUG! Is that a paisley?! I hate paisley!'] },
    ],
    bleedCap: 0.24,
    outro: [
      ['MACK', 'We got the gold back. The rainbow in the vault apologized to Mr. Pennyworth and then evaporated. Nobody wrote that part down.'],
      ['SALLY', 'One of the Rollers kept looking up at the sky. Like he was waiting for a ride.'],
      ['MACK', 'And the getaway money was in bags stamped "Krane for Mayor." Our Mayor. The man with his own gold statue in Krane Plaza.'],
      ['MACK', 'Everybody in this town is waiting for something. Usually it\'s the rain to stop. It doesn\'t.'],
    ],
    clue: { text: 'The heist boys use paint that washes off easy. Every one you drop, the rain takes twice the color with him.', effects: ['bigWash'] },
    gus: 'Rollers are slow and mean. Run \'em over if you\'re in the car. It\'s legal. Mostly.',
  },
  {
    id: 4, title: 'Holes in the Sky', district: 'Old Town', music: 'high',
    dame: { name: 'Professor Ingrid Holloway', hat: 'beret', shade: 0x5a5a5a, fur: false },
    blurb: 'A physicist reports actual holes in the sky over Old Town. Something on the other side is humming show tunes.',
    intro: [
      ['sleep', 'NARR', 'Monday. Lightning hit the same lamppost three times. It was asking for it.'],
      ['dameIn', 'NARR', 'She had a slide rule, a lab coat, and the look of a woman who\'d just been proven right and hated it.'],
      [null, 'DAME', 'Professor Holloway, City Institute of Unlikely Sciences. I need your employer. Urgently.'],
      [null, 'DOTTIE', 'Unlikely science! I\'m unlikely science! *hic* My inventor said I was "a mistake with a typing speed."'],
      [null, 'DAME', 'Fascinating. Are you running on bourbon?'],
      [null, 'DOTTIE', 'Rye. Bourbon makes me sentimental. Last time I proposed to a parking meter.'],
      ['dameDesk', 'NARR', 'She set a photograph on my desk. It was the sky. The sky had a hole in it.'],
      ['wake', 'MACK', 'That\'s a nice picture of a doughnut, lady.'],
      [null, 'DAME', 'It is a PORTAL, Mr. Malone. A tear in the sky over Old Town. On the other side there is a dimension made entirely of color. And it is humming. Show tunes.'],
      [null, 'MACK', 'Which show?'],
      [null, 'DAME', 'All of them.'],
      ['sallyIn', 'SALLY', 'MACK. MACK. THE SKY IS LEAKING! There\'s holes and guys are falling out of them with buckets and one of them winked at me!'],
      [null, 'SALLY', 'I rocketed him. He stopped winking.'],
      ['stamp', 'MACK', 'Holes in the sky. Fine. A hole\'s just a door nobody asked for. Let\'s go close some doors.'],
    ],
    stages: [
      { text: 'Close the portals tearing open over Old Town', goal: { type: 'portals', n: 3 }, portals: 3, mix: { dauber: 0.5, hood: 0.4, roller: 0.1 }, max: 8, interval: 2.6, line: ['MACK', 'Those things spit out Syndicate like a slot machine. Shoot the ring till it closes. Sally — anything that hums, rocket it.'] },
      { text: 'More holes — and Paintbots rolling out of them. Close the holes', goal: { type: 'portals', n: 2 }, portals: 2, roombas: 2, mix: { hood: 0.3, goon: 0.3, roller: 0.2, dauber: 0.2 }, max: 10, interval: 2.0, line: ['SALLY', 'Two MORE? Mack, the sky is just a big Swiss cheese now. Grey Swiss cheese. With holes. That\'s just Swiss cheese, Mack.'] },
    ],
    bleedCap: 0.25,
    outro: [
      ['MACK', 'The holes closed. The humming stopped. Somewhere a dimension made of color was halfway through "Oklahoma!" and lost its audience.'],
      ['SALLY', 'Before the last one closed I saw something through it. A big casino. Brighter than ours. With a sign.'],
      ['MACK', 'What did it say?'],
      ['SALLY', '"COMING SOON: THE STRIP."'],
    ],
    clue: { text: 'Those holes in the sky? Professor came in after you left. Said the rings are brittle — they crack at half the beating you\'d think.', effects: ['portalWeak'] },
    gus: 'Portals keep spitting goons till they\'re closed. Ignore the small fry and shoot the ring.',
  },
  {
    id: 5, title: 'Snake Eyes on the Strip', district: 'The Strip', music: 'high',
    dame: { name: 'Countess Valentina Vex', hat: 'wide', shade: 0x1a1a1a, fur: true },
    blurb: 'The slot machines at the Silver Dollar pay out in jellybeans. The croupiers are wearing plaid. The Prism Palace opened overnight across the street.',
    intro: [
      ['sleep', 'NARR', 'Friday. The rain was falling sideways now. Even the weather was trying to get out of town.'],
      ['dameIn', 'NARR', 'She smelled like money, cigarettes and a lawsuit.'],
      [null, 'DAME', 'Countess Valentina Vex. I own the Silver Dollar. I do not wait in waiting rooms.'],
      [null, 'DOTTIE', 'Of course, Countess. *hic* Please wait in this room, which is a waiting room. I\'ll wait with you. I\'m great at waiting. I\'ve been waiting for love since 1946.'],
      ['dameDesk', 'NARR', 'She didn\'t sit down. Women like that don\'t sit; they let the room arrange itself around them.'],
      ['wake', 'MACK', 'Countess. You\'re a long way from the Strip.'],
      [null, 'DAME', 'My slot machines now pay out in jellybeans, Malone. My croupiers wear PLAID. A new casino — the Prism Palace — opened across the street overnight. It has no doors. People just... smile and walk into the wall.'],
      [null, 'MACK', 'Sounds like a regular Tuesday on the Strip.'],
      [null, 'DAME', 'It is Friday.'],
      ['sallyIn', 'SALLY', 'MACK! Lowriders! Painted lowriders cruising the Strip and painting stripes down the boulevard! The driver\'s a guy called Chartreuse Charlie and he has a DRUM GUN!'],
      [null, 'SALLY', 'Also I won forty dollars in jellybeans.'],
      ['stamp', 'MACK', 'All right. We\'re going to the Strip. Dottie — no gambling while we\'re gone.'],
      [null, 'DOTTIE', 'I would never. *hic* I bet you twenty I would never.'],
    ],
    stages: [
      { text: 'Run the Syndicate off the Strip', goal: { type: 'kill', n: 16 }, mix: { hood: 0.35, dauber: 0.2, lowrider: 0.2, roller: 0.15, truck: 0.1 }, max: 10, interval: 1.7, line: ['MACK', 'The Strip. A mile of lights trying to sell you something you already lost.'] },
      { text: 'A fleet of Paintbots is turning the Strip into a rainbow — scrap them', goal: { type: 'roombas', n: 3 }, roombas: 3, mix: { hood: 0.35, goon: 0.25, lowrider: 0.25, dauber: 0.15 }, max: 10, interval: 1.8, line: ['MACK', 'Three of them. Rolling down the boulevard like they own it. Painting stripes on the casinos.'] },
      { text: 'Close the portals feeding the Prism Palace', goal: { type: 'portals', n: 2 }, portals: 2, mix: { hood: 0.4, goon: 0.2, lowrider: 0.3, dauber: 0.1 }, max: 10, interval: 1.8 },
      { text: 'Chartreuse Charlie — end his lucky streak', goal: { type: 'boss' }, boss: 'charlie', mix: { lowrider: 0.5, hood: 0.5 }, max: 5, interval: 3, line: ['SALLY', 'He\'s GREEN, Mack! Like, really green! Like a frog ate a lime!'] },
    ],
    bleedCap: 0.26,
    outro: [
      ['MACK', 'Chartreuse Charlie crapped out. The Prism Palace folded up like a bad hand and blew away down the boulevard.'],
      ['SALLY', 'The cops showed up after. Well. One cop. To ask if anybody had seen a cruller.'],
      ['MACK', 'Every rat on the Strip ran south. Toward Southside. Toward the Holy Glaze.'],
    ],
    clue: { text: 'Charlie\'s lowriders run on Prism juice. One good rocket in the tank and they go up like the Fourth of July. And Charlie himself? Gin-soaked. Rockets love gin.', effects: ['lowriderWeak', 'rocket2x'] },
    gus: 'Lowriders paint stripes as they drive. Ram \'em, rocket \'em, or get out and shoot the driver.',
  },
  {
    id: 6, title: 'Glazed and Confused', district: 'Southside', music: 'high',
    dame: { name: 'Doris Hogg', hat: 'cloche', shade: 0x7a7570, fur: false },
    blurb: 'The Police Commissioner hasn\'t left the Holy Glaze in nine days. Yesterday he turned pink. His wife thinks he\'s becoming a frosted cruller.',
    intro: [
      ['sleep', 'NARR', 'Sunday. The rain was so heavy the gutters were taking reservations.'],
      ['dameIn', 'NARR', 'She was a cop\'s wife. You can always tell. They look at the door like it owes them money.'],
      [null, 'DAME', 'Doris Hogg. My husband is the Police Commissioner.'],
      [null, 'DOTTIE', 'Oh no. *hic* Are we in trouble? Is it about the parking meter? We broke up. It was mutual.'],
      [null, 'DAME', 'It\'s about my husband. He went to the Holy Glaze for a "working lunch" nine days ago.'],
      ['dameDesk', 'NARR', 'Every cop in Rain City goes to the Holy Glaze for a working lunch. Nobody has ever seen the work.'],
      ['wake', 'MACK', 'Nine days is a long lunch, even for Hogg.'],
      [null, 'DAME', 'Yesterday he turned pink, Mr. Malone. He has SPRINKLES. He keeps saying "I am glazed, Doris. I am finally glazed." The Syndicate is putting Prism in the frosting.'],
      [null, 'MACK', 'So every cop in town is eating color by the dozen. Explains why they never show up. Not that they ever did.'],
      ['sallyIn', 'SALLY', 'MACK! The Southside is going full pastel! Portals all around the donut shop! And the Commissioner — Mack, the Commissioner is THIRTY FEET TALL and made of FROSTING!'],
      [null, 'DAME', '...Is he at least happy?'],
      [null, 'SALLY', 'He looks VERY happy, ma\'am.'],
      ['stamp', 'MACK', 'Then this one\'s going to hurt him more than it hurts me. Let\'s go.'],
    ],
    stages: [
      { text: 'Close the portals ringing the Holy Glaze', goal: { type: 'portals', n: 3 }, portals: 3, mix: { dauber: 0.4, hood: 0.4, roller: 0.2 }, max: 10, interval: 1.8, line: ['MACK', 'The Holy Glaze. Ten cruisers out front and not a cop in sight who isn\'t chewing.'] },
      { text: 'Hold Southside — clear the Syndicate and scrap their Paintbots', goal: { type: 'kill', n: 18 }, roombas: 2, mix: { hood: 0.3, goon: 0.2, roller: 0.25, lowrider: 0.25 }, max: 11, interval: 1.5 },
      { text: 'Commissioner Cruller. Bring him back down to size', goal: { type: 'boss' }, boss: 'cruller', mix: { dauber: 0.5, hood: 0.5 }, max: 6, interval: 2.5, line: ['SALLY', 'He\'s throwing DONUTS at us! Giant pink donuts! Mack, I want one so bad and I also want to rocket him!'] },
    ],
    bleedCap: 0.27,
    outro: [
      ['MACK', 'The Commissioner shrank back down to regular size. Still round. Still pink around the edges. Still eating.'],
      ['SALLY', 'He gave us a tip. Said the King is shipping something big out of the Union Rail Yard. Then he asked if we had any donuts.'],
      ['MACK', 'The King. So there\'s a King now. In my city we only had one king, and he was a rat named Lenny.'],
      ['SALLY', 'He also said the frosting invoices went to City Hall. Signed by the Mayor. In glitter pen.'],
    ],
    clue: { text: 'Hogg\'s sprinkles? Rain-soluble. Every goon you put down out there, the storm\'ll wash twice the color with him.', effects: ['bigWash', 'extraFlask'] },
    gus: 'The cops at the Holy Glaze won\'t help you. They won\'t even look up. You could rocket the parking lot and they\'d just ask for a napkin.',
  },
  {
    id: 7, title: 'The Sunrise Express', district: 'Rail Yards', music: 'high',
    dame: { name: 'Madame Magenta', hat: 'veil', shade: 0x3a3a3a, fur: true, gang: '#ff2d95' },
    blurb: 'A client walks in glowing pink: Madame Magenta, the Syndicate\'s own. She says the King is shipping an actual sunrise out of the rail yard in boxcars.',
    intro: [
      ['sleep', 'NARR', 'Wednesday. The rain had gotten so heavy it was coming down in sheets. Monogrammed sheets.'],
      ['dameIn', 'NARR', 'She walked in pink. Not a little pink. The kind of pink that shows up in your dreams and charges rent.'],
      [null, 'DOTTIE', 'Whoa. *hic* Ma\'am, you\'re in COLOR. That\'s against the... the... I forget. I had a whole thing.'],
      [null, 'DAME', 'Darling, I am Madame Magenta. I am the competition. And I am here to hire the detective.'],
      [null, 'DOTTIE', 'He doesn\'t work for color people. *hic* He doesn\'t work for anybody. He barely works.'],
      ['dameDesk', 'NARR', 'She sat on my desk. On my case files. On my sandwich. Sally\'s sandwich, technically.'],
      ['wake', 'MACK', 'Lady, you\'re glowing on my furniture.'],
      [null, 'DAME', 'The King is shipping a SUNRISE out of the Union Rail Yard, Malone. A whole sunrise, packed in boxcars. If it gets out, there will be no more night in Rain City. No more rain. No more grey. No more... you.'],
      [null, 'MACK', 'And what\'s in it for you?'],
      [null, 'DAME', 'Darling. A girl can\'t sell Prism in a city where everybody\'s already happy.'],
      ['sallyIn', 'SALLY', 'Mack, the rail yard is going all orange and gold and SUNSHINY — oh. Hi. You\'re pink. I don\'t like you.'],
      [null, 'DAME', 'Your little friend has a rocket launcher.'],
      [null, 'SALLY', 'My little friend has TWO rocket launchers. One\'s in the car.'],
      ['stamp', 'MACK', 'We\'ll stop the train. But you\'re not my client, lady. You\'re my next case.'],
    ],
    stages: [
      { text: 'Break the King\'s crews at the Union Rail Yard', goal: { type: 'kill', n: 18 }, mix: { hood: 0.3, roller: 0.25, lowrider: 0.15, dauber: 0.15, truck: 0.15 }, max: 12, interval: 1.4, line: ['MACK', 'The boxcars glowed like somebody left the oven open. Somebody had packed a sunrise in there. Somebody was going to regret it.'] },
      { text: 'Close the portals loading the Sunrise Express', goal: { type: 'portals', n: 3 }, portals: 3, mix: { hood: 0.4, roller: 0.3, lowrider: 0.3 }, max: 12, interval: 1.5 },
      { text: 'Double-cross: Madame Magenta wants the sunrise for herself', goal: { type: 'boss' }, boss: 'magenta', mix: { hood: 0.5, dauber: 0.5 }, max: 6, interval: 2.5, line: ['SALLY', 'I KNEW IT! I knew it the second she sat on the sandwich!'] },
    ],
    bleedCap: 0.28,
    outro: [
      ['MACK', 'Magenta went grey and the sunrise went back in its box. We dropped the box in the harbor. Somewhere under the dishwater, there\'s a morning that\'ll never come.'],
      ['SALLY', 'Mack, she said one thing before she faded. "Krane sold the city. Every last shade of grey. Ask the Mayor who signed the deed."'],
      ['MACK', 'Mayor Horace Krane. Tomorrow we go to City Hall, Sally. And we don\'t knock.'],
      ['SALLY', 'We never knock.'],
    ],
    clue: { text: 'Magenta\'s whole act is held together with hairspray. Highly explosive hairspray. Sally\'s rockets\'ll do double.', effects: ['rocket2x'] },
    gus: 'You\'re running hot, Mack. Take the extra flask. It\'s on the house. Everything\'s on the house. The house is on fire, probably.',
  },
  {
    id: 8, title: 'Hizzoner', district: 'Civic Center', music: 'high',
    dame: { name: 'Miss Dolores Fitch', hat: 'cloche', shade: 0x4a4a4c, fur: false },
    blurb: 'The Mayor\'s own stenographer walks in with a ledger. Horace Krane has been selling Rain City\'s grey to the Syndicate, one shade at a time.',
    intro: [
      ['sleep', 'NARR', 'Tuesday. The rain was so thick you could lean on it. Half of Old Town was.'],
      ['dameIn', 'NARR', 'She held a ledger to her chest like it was a baby or a bomb. In this town, those are the same thing.'],
      [null, 'DOTTIE', '*hic* Welcome to Malone Investigations. Are you here about the parking meter? Because it was HIS idea.'],
      [null, 'DAME', 'Dolores Fitch. I take dictation for the Mayor. Took. I think I just quit.'],
      [null, 'DOTTIE', 'I take dictation too! *hic* Mostly from the radio. Mostly the weather. It\'s always rain. I just write "rain."'],
      ['dameDesk', 'NARR', 'She put the ledger on my desk. It was heavier than a ledger ought to be. Guilt has weight.'],
      ['wake', 'MACK', 'That\'s City Hall stationery. You\'re either very brave or very lost.'],
      [null, 'DAME', 'Every payment from the Technicolor Syndicate, Mr. Malone. In the Mayor\'s own handwriting. He sold them the color rights to Rain City. All of it. The rain included.'],
      [null, 'MACK', 'Horace Krane. Built himself a forty-foot gold statue with the parking-ticket money. Never trusted a man who waves at himself.'],
      [null, 'DAME', 'There\'s worse. The statue moves now. At night. It goes for walks. It waves at children.'],
      ['sallyIn', 'SALLY', 'MACK! Krane Plaza is going GOLD! The Mayor\'s got Syndicate goons for bodyguards and he\'s giving a speech about how "a brighter city starts with a brighter Mayor"!'],
      [null, 'SALLY', 'He has a SASH, Mack. The sash says "MAYOR." In sequins.'],
      ['stamp', 'MACK', 'Then let\'s go cast my vote. Dottie, call the papers. Tell them to save the front page.'],
      [null, 'DOTTIE', '*hic* I\'ll call ALL the papers. I\'ll call the paper towels too. Just in case.'],
    ],
    stages: [
      { text: 'Break Krane\'s Syndicate bodyguards in the Civic Center', goal: { type: 'kill', n: 18 }, mix: { hood: 0.4, roller: 0.25, dauber: 0.2, truck: 0.15 }, max: 12, interval: 1.4, line: ['MACK', 'City Hall. Marble steps, gold statue, and a crooked man at the top of both.'] },
      { text: 'Krane bought the Paintbots with city money. Scrap them all', goal: { type: 'roombas', n: 3 }, roombas: 3, mix: { goon: 0.5, hood: 0.5 }, max: 10, interval: 1.6, line: ['SALLY', 'They have little KRANE stickers on them! He EXPENSED them!'] },
      { text: 'Close the portals Krane opened under his own plaza', goal: { type: 'portals', n: 3 }, portals: 3, mix: { hood: 0.3, goon: 0.2, roller: 0.25, lowrider: 0.25 }, max: 12, interval: 1.5, line: ['SALLY', 'He put PORTALS in the PUBLIC FOUNTAINS. That\'s not even legal! Is it? Mack, is it legal?'] },
      { text: 'Mayor Horace Krane, on the steps of City Hall. Impeach him', goal: { type: 'boss' }, boss: 'krane', mix: { hood: 0.6, roller: 0.4 }, max: 6, interval: 2.4, line: ['MACK', 'Mister Mayor. You\'re under arrest for selling the color of my city. And for that sash.'] },
    ],
    bleedCap: 0.28,
    outro: [
      ['MACK', 'Horace Krane went down on his own marble steps. The gold drained out of his suit and the sequins fell off his sash one by one, like a slow applause.'],
      ['SALLY', 'Before he went grey he laughed. He said "You think I\'m the top, Malone? I just signed the papers. The buyer\'s coming through tonight."'],
      ['MACK', 'The buyer. The Prism King. He bought a city, and tonight he comes to collect.'],
      ['SALLY', 'Can we stop him? Say we can stop him. I\'ll stop him by myself if I have to. I named a rocket after him. It\'s called "Stopping Him."'],
    ],
    clue: { text: 'Krane\'s bodyguards are on the city payroll, and the city stopped paying \'em this morning. Every one you drop, the color goes with him — double.', effects: ['bigWash', 'rocket2x'] },
    gus: 'Krane drinks here, you know. Tips in campaign buttons. If you\'re going after him, take the extra flask. He fights dirty. He fights with money.',
  },
  {
    id: 9, title: 'The Last Grey Morning', district: 'City', music: 'boss',
    dame: { name: 'Miss Grey', hat: 'veil', shade: 0xb0b0b0, fur: false, ghost: true },
    blurb: 'The last client is the city herself. A pale woman made of rain and newsprint. The Prism King is coming through the sky over City Hall.',
    intro: [
      ['sleep', 'NARR', 'The last night. The rain fell so hard it forgot how to stop. I didn\'t mind. I\'d never seen it stop anyway.'],
      ['dameIn', 'NARR', 'She came in without opening the door. She was pale as newsprint and she smelled like wet pavement and old jazz.'],
      [null, 'DOTTIE', '*hic*... ma\'am, you\'re... you\'re dripping. You\'re made of DRIPPING. Are you a... a weather?'],
      [null, 'DAME', 'Close, dear. I\'m the city.'],
      [null, 'DOTTIE', 'Oh. *hic* I\'ve been living in you this whole time. I\'m so sorry about the oil stains.'],
      ['dameDesk', 'NARR', 'I knew her face. I\'d seen it in every puddle in town.'],
      ['wake', 'MACK', 'I know you.'],
      [null, 'DAME', 'You\'ve lived in me your whole life, Mack. I\'m Rain City. And tonight a man made of light is coming through the sky to paint me over. Every alley. Every bar. Every last grey morning.'],
      [null, 'MACK', 'I can\'t pay you back for all the rain, lady. But I can pay him back for the color.'],
      [null, 'DAME', 'Krane sold me, Mack. Every alley, every gutter. The King has the deed. Tear it up.'],
      ['sallyIn', 'SALLY', 'Mack! The sky over City Hall just opened like a jewelry box! There\'s a guy with a PRISM for a head and he\'s singing about how beautiful we\'re all going to be!'],
      [null, 'SALLY', 'I already hate him so much. Can I hate him with rockets?'],
      [null, 'DOTTIE', 'Malone. *hic* If you don\'t come back... can I have your flasks?'],
      ['stamp', 'MACK', 'You already have my flasks, Dottie. Let\'s go, Sally. One more case.'],
    ],
    stages: [
      { text: 'The sky is open all over town — close the portals', goal: { type: 'portals', n: 4 }, portals: 4, mix: { hood: 0.35, roller: 0.25, lowrider: 0.2, dauber: 0.2 }, max: 12, interval: 1.4, line: ['MACK', 'Holes everywhere. The whole sky looked like a moth got at it.'] },
      { text: 'Paintbots in every district — scrap them before the city is one big rainbow', goal: { type: 'roombas', n: 4 }, roombas: 4, mix: { goon: 0.35, hood: 0.3, lowrider: 0.35 }, max: 12, interval: 1.3 },
      { text: 'Hold the line — the Syndicate is everywhere', goal: { type: 'kill', n: 22 }, mix: { hood: 0.2, goon: 0.2, roller: 0.2, lowrider: 0.2, truck: 0.2 }, max: 13, interval: 1.2 },
      { text: 'The Prism King, on the steps of City Hall', goal: { type: 'boss' }, boss: 'king', mix: { hood: 0.4, roller: 0.3, dauber: 0.3 }, max: 8, interval: 2.2, line: ['SALLY', 'He\'s HUGE and he\'s SPARKLY and his head is a TRIANGLE. Mack, this is the best and worst night of my life.'] },
    ],
    bleedCap: 0.075,
    outro: [
      ['MACK', 'The Prism King shattered like a dropped highball. A million little rainbows fell on City Hall and the rain washed every one of them into the sewer.'],
      ['SALLY', 'Mack... look. It\'s morning. It\'s grey. It\'s raining.'],
      ['MACK', 'Most beautiful thing I ever saw.'],
      ['NARR', 'Back at the office, Dottie had married the coffee machine. Sally caught the bouquet and rocketed it. The rain kept falling.'],
      ['MACK', 'Rain City. My city. Grey as a gravestone and twice as honest. I\'ll take it.'],
    ],
    clue: { text: 'The King\'s portals are made of the same cheap glass as his head. They\'ll crack quicker than you think. And take these flasks — all of \'em.', effects: ['portalWeak', 'extraFlask'] },
    gus: 'If you\'re going after the King, Mack, leave a tab open. I\'d like to think you\'re coming back to pay it.',
  },
];

// Off the books: no client, no clock, no fail. Just you, Sally, and every goon in town.
export const PATROL = {
  id: 0, title: 'Night Patrol', district: 'City', music: 'high', patrol: true,
  dame: { name: 'Nobody', hat: 'cloche', shade: 0x555555 },
  blurb: 'No client. No case. Just Mack, Sally, the Packard and a city full of colorful targets. Shoot them, run them over, blow up their trucks.',
  intro: [], outro: [],
  stages: [
    { text: 'Night patrol — shoot, ram and rocket anything colorful', goal: { type: 'goto', at: 'casino', r: 30, label: 'THE STRIP' }, mix: { dauber: 0.3, hood: 0.3, goon: 0.2, truck: 0.2 }, max: 10, interval: 1.6, roam: true, line: ['SALLY', 'Off the books, Mack! Nobody\'s paying us, so everything\'s FREE!'] },
    { text: 'Keep the streets grey. As long as you like', goal: { type: 'kill', n: 99999 }, mix: { dauber: 0.2, hood: 0.25, goon: 0.2, roller: 0.1, lowrider: 0.1, truck: 0.15 }, max: 16, interval: 1.1, roam: true, roombas: 2 },
  ],
  bleedCap: 99,
};

export const BOSSES = {
  vic: { name: 'Vic Vermilion', sub: 'Owner of the Kaleidoscope Club', color: '#ff5a1f', hp: 900, scale: 1.6, speed: 6.5, at: 'club', attack: 'shotgun', summon: 'hood' },
  charlie: { name: 'Chartreuse Charlie', sub: 'King of the Lowriders', color: '#9dff1a', hp: 1400, scale: 1.7, speed: 7, at: 'palace', attack: 'drum', summon: 'lowrider' },
  cruller: { name: 'Commissioner Cruller', sub: 'Formerly Commissioner Hogg', color: '#ff7ac8', hp: 1900, scale: 3.0, speed: 4.2, at: 'donut', attack: 'donuts', summon: 'dauber' },
  krane: { name: 'Mayor Horace Krane', sub: 'Re-Elect Krane: A Brighter City', color: '#ffd35a', hp: 2600, scale: 1.9, speed: 5.5, at: 'plaza', attack: 'money', summon: 'hood' },
  magenta: { name: 'Madame Magenta', sub: 'The Double-Cross', color: '#ff2d95', hp: 2200, scale: 1.9, speed: 7.5, at: 'rail', attack: 'bombs', summon: 'roller' },
  king: { name: 'The Prism King', sub: 'He Wants You Beautiful', color: '#ffffff', hp: 4200, scale: 2.6, speed: 5.5, at: 'cityHall', attack: 'beam', summon: 'portal' },
};

export const LINES = {
  kill: ['Lights out, sunshine.', 'Back to grey, pal.', 'Another one for the gutter.', 'Color me unimpressed.', 'The rain\'ll wash you out by morning.', 'That\'s the trouble with color. It runs.', 'You picked the wrong city to be cheerful in.', 'Nothing personal. Okay, a little personal.', 'Stay grey, kid.', 'Rest in black and white.'],
  sallyRocket: ['ROCKET!', 'Bye-bye!', 'Wheee!', 'Special delivery!', 'Did you see that one, Mack?!', 'I love my job!', 'That one had a little hat!', 'Kaboom, honey!', 'More rockets! More!', 'Hold still, sweetie!'],
  carIn: ['Shotgun! Well — rocket-gun!', 'Drive, Mack! I\'ll do the shooting!', 'Window\'s down, launcher\'s up!', 'Floor it, handsome!'],
  carOut: ['Right behind you, Mack!', 'On foot? Ooh, close-range rockets!', 'I\'m coming too! I\'m always coming too!'],
  pills: ['Pain pills. Here comes the color. I hate this part.', 'Everything\'s turquoise again. I want to die.', 'The sky is BLUE. Who did this. Who made the sky blue.', 'Pills kick in. The world turns into a circus poster. Ugh.', 'Sally\'s dress is the only thing that looks right. Everything else looks like a candy store threw up.'],
  pillsOff: ['There it is. Grey. Beautiful grey.', 'Color\'s gone. Thank God.', 'Back to normal. Back to rain.'],
  noPills: ['Out of pills. Good.'],
  flask: ['Medicinal.', 'For my nerves. All of them.', 'Breakfast of private investigators.', 'The good stuff. Well, the stuff.', 'Rain outside, rye inside.'],
  noFlask: ['Empty. Like my bank account.', 'Dry as a sermon.'],
  hurt: ['That one stung.', 'I\'m getting too old for paintballs.', 'Somebody\'s going to pay for this coat.'],
  bleed: ['The color\'s spreading. Gotta put some of these clowns down.', 'The whole block\'s going Technicolor. Move, Malone.', 'Too much color, not enough corpses.'],
  portal: ['Another hole in the sky. Somebody call a roofer.', 'Portal. The sky\'s got more holes than my alibi.', 'There goes the sky again.'],
  close: ['Shut. Like a bar at 2 a.m.', 'That\'s one less door.', 'Closed. Somebody tell the show tunes.'],
  carDead: ['There goes the car.', 'That was a rental.'],
  sallyCarDead: ['Don\'t worry, Mack, I\'ll boost us another one!'],
};

// The Holy Glaze. Every time Mack or Sally drive past, somebody says it.
export const DONUT_LINES = [
  ['MACK', 'Holy Glaze. Ten cruisers out front and not a cop on the street. Fat pigs at the trough.'],
  ['SALLY', 'Oink oink, boys! Save me a cruller, you fat pigs!'],
  ['MACK', 'City\'s drowning in color and the boys in blue are drowning in sprinkles. Fat pigs.'],
  ['SALLY', 'Can I rocket the donut shop? Just a little? Those fat pigs wouldn\'t even notice.'],
  ['MACK', 'Every cop in the precinct, lined up like piglets at a teat. Fat pigs.'],
  ['MACK', 'Same donut shop, same fat pigs. Only thing they ever closed is a box of a dozen.'],
  ['SALLY', 'Look, Mack, the fat pigs are hibernating!'],
  ['MACK', 'If the Syndicate painted that whole shop pink, those fat pigs wouldn\'t notice till the glaze tasted different.'],
  ['SALLY', 'Hey fat pigs! A crime is happening! It\'s us! We\'re speeding!'],
  ['MACK', 'Holy Glaze. Where justice goes to get a jelly-filled. Fat pigs.'],
  ['SALLY', 'Bet those fat pigs couldn\'t catch a cold. Or a donut. Wait, they can catch donuts.'],
  ['MACK', 'Protect and serve. Serve themselves, mostly. Fat pigs.'],
];
export const COP_RETORTS = ['Keep drivin\', Malone!', 'It\'s a workin\' lunch!', 'These are EVIDENCE!', 'We\'re on break! Since Tuesday!', 'Mmmf! Mmf mmf!', 'Hey! We\'re big-boned!', 'Go solve somethin\'!', 'You want a bear claw or not?'];

export const DOTTIE_IDLE = [
  '*hic* Malone Investigations, how may I misdirect your call?',
  'I\'m not drunk, I\'m running a diagnostic. On rye.',
  'Sally borrowed my left arm again. For "a thing."',
  'The coffee machine and I are taking it slow. *hic*',
  'You have... *hic* ...forty-one new messages. All from me. To you. I miss you when you nap.',
  'If anybody asks, the flasks are filing cabinets. Tiny ones. For liquid files.',
];

export const GUS_HINTS = [
  'Pain pills on G. They patch you right up, but you\'ll see the whole world in color for a spell. Mack hates it. Everybody hates it.',
  'F puts you in Focus. Time crawls, your revolver doesn\'t. Runs on the color you take off the Syndicate, so drop goons to fill it back up.',
  'Right mouse to draw the big red one, left to fire. Holster it a second and you\'ll thumb in fresh rounds. Six shots, Mack. Count \'em.',
  'Hit Q to pull from the flask. Puts grit back in you, and for a few seconds the whole world slows down. Rye\'s funny like that.',
  'Space in the car is the handbrake. Throw it around a corner and Sally stays on target.',
  'Paintbots are big dumb robot vacuums full of paint. Don\'t ram \'em — they\'re built like bank vaults. Get Sally\'s rockets on \'em.',
  'The fella in the rainbow trenchcoat? Rainbow Goon. Shoots in threes. Don\'t stand in a line.',
  'Every Syndicate you drop, the rain washes the color out around him. Keep the killing up and the bleed goes down.',
  'R on foot is a tuck and roll. Paintballs can\'t hit what\'s lying in a puddle.',
  'The City Infection meter? Every goon paints as he walks. If it fills, the city goes full Technicolor, you lose your lunch and the case. Don\'t let it fill.',
  'Click in the car and Sally fires wherever you point. She\'ll pick her own targets otherwise. She always does.',
  'Burning barrels in the empty lots? Folks stash flasks by \'em. Look around.',
  'This bar\'s on the map, Mack. Walk in mid-case and I\'ll patch you up once. Once.',
];

export const DAME_PORTRAIT_FALLBACK = 'A dame.';
